### ISSUE TITLE
Ability to resize the icons at the bottom

### ISSUE THREAD

**Issue by wdblue34** [Samillion/ModernZ#100]
As the title suggests, I'd like to suggest the implementation of the ability to resize the icons to address different user configurations
![mpv_eIYWRhzNOi](https://github.com/user-attachments/assets/cdef3121-bc1b-4a0e-b64f-7cf434d90253)

I couldn't do it with .config file, therefore I wanted to suggest it here. In short, I just wanted to move the seekbar a little bit down by resizing these buttons, can you help me with that?

Edit:
I know this feature will not suit the title but I didn't want to create a new PR.
Could you add an option to hide subtitles button?

**Comment by Samillion** [comment]
Noted. Will add them as options in the next release.

I never thought anyone would want subtitle button hidden, so I'll make the audio track button option as well.
