### ISSUE TITLE
Add option to change the speed of the video

### ISSUE THREAD

**Issue by wdblue34** [Samillion/ModernZ#101]
Title suggests it all. There should be a visual option to change the videos speed like 1.25 , 1.5 and 2.

Best regards

**Comment by Samillion** [comment]
This is already set as a keybind if you're using the default ones:
https://mpv.io/manual/master/#keyboard-control

Alternatively, you can set custom keybind in your `input.conf` to achieve that
https://mpv.io/manual/master/#options-speed

**Comment by Samillion** [comment]
Done with: https://github.com/Samillion/ModernZ/pull/127

In `modernz.conf` add `seekbar_track_wheel_mode=speed`

| Type                          | Option                           | Function                                                                                 |
| ----------------------------- | -------------------------------- | ---------------------------------------------------------------------------------------- |
| Seekbar Mode (mouse wheel)    | seekbar_track_wheel_mode         | default: `seek`<br> accepts `seek` or `speed`.<br>`speed` changes playback speed up/down |

Full details in [mouse actions](https://github.com/Samillion/ModernZ/blob/main/docs/USER_OPTS.md#mouse-commands-user-options).
