### ISSUE TITLE
Can you add Playback speed toggle ?

### ISSUE THREAD

**Issue by houssemko** [Samillion/ModernZ#106]
A toggle that can be used with the mouse wheel to increase and decrease playback speed

**Comment by Samillion** [comment]
At the moment, if you use the mouse wheel on seekbar, it seeks backwards/forwards.

I can make that configurable so that you set your own behavior, whether it's speed or whichever else. Sound good?

**Comment by houssemko** [comment]
Yes sounds good .

**Comment by Samillion** [comment]
Done with: https://github.com/Samillion/ModernZ/pull/127

In `modernz.conf` add `seekbar_track_wheel_mode=speed`

| Type                          | Option                           | Function                                                                                 |
| ----------------------------- | -------------------------------- | ---------------------------------------------------------------------------------------- |
| Seekbar Mode (mouse wheel)    | seekbar_track_wheel_mode         | default: `seek`<br> accepts `seek` or `speed`.<br>`speed` changes playback speed up/down |

Full details in [mouse actions](https://github.com/Samillion/ModernZ/blob/main/docs/USER_OPTS.md#mouse-commands-user-options).
