### ISSUE TITLE
Indicate if audio and subtitle tracks are disabled

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#109]
At a glance, there's no way to tell that the available audio/sub track(s) are toggled off until you see the `Subtitle -/1 [n/a]` tooltip.

Should the icons be grayed out or have a different icon to help differentiate that?

**Comment by Samillion** [comment]
Terribly sorry about the late response. I've been out of home most of the time lately, so schedules are a bit erratic.

What color by default you think would be suitable for this? or should they just be grayed out?

**Comment by Keith94** [comment]
Lately I was thinking of adding a border on the bottom (like YouTube's) to clearly see when subtitles are enabled.

Available and turned on:
![brave_LipED4pdJI](https://github.com/user-attachments/assets/4f4dd3aa-904b-40c0-a86a-2a123704d9e1)

Available but turned off:
![brave_4AUMblKmDQ](https://github.com/user-attachments/assets/ae148b87-fb31-49aa-a18a-fdaddec48c20)

None available:
![brave_tTs7jffTt7](https://github.com/user-attachments/assets/532e2823-d10f-4292-8058-b0cbdb90ba96)

Do you think that's doable? Although I would only apply it to subtitles, audio can remain untouched.

**Comment by Keith94** [comment]
With that said, it's probably a lot less work to implement a simple grayed-out appearance.
That's what old forks of the project used to do, too:

https://github.com/user-attachments/assets/dd7b2e85-5974-4d65-8cac-dc883587ae24
