### ISSUE TITLE
show current chapter & chapter remaining time

### ISSUE THREAD

**Issue by mrfragger** [Samillion/ModernZ#11]
The select.lua works well with the mouse and selecting with mouse...couldn't figure out g-l, g-c, stuff till a few hours ago and finally saw oh it's not just playlist but for chapters and other stuff.  Now might re-do some keybindings using a leader key or whatever that thing is called.

So is select.lua ever gonna have a file browser or is it drag and drop into mpv or find the file in the file manager and open it pretty much?  History - memo works ..just can't search like in usoc.  

So in uosc some things I really like are shows current chapter, chapter remaining time.  Helps when you wanna set a sleep timer for x mins or whatever the remaining chapter time is.
<img width="875" alt="image" src="https://github.com/user-attachments/assets/45a4fdd2-ba52-4f8b-bb39-68147d928a75">

**Comment by Samillion** [comment]
Right now it's in the process of being improved, specifically mouse control support. We've been having discussions about it over at mpv:

https://github.com/mpv-player/mpv/pull/15016
https://github.com/mpv-player/mpv/pull/15031

As of now, expect it to behave as an interactive playlist or track list. But honestly, I see it evolving in the future. Guidocell has been doing amazing work so far.

I'll integrate it more in this OSC for chapters and anywhere possible soon. Just waiting for mouse control stuff to be out there

**Comment by mrfragger** [comment]
yea I'm aware of those threads or at least the first one I was...how do ya think I found out about ModernZ..hehe.  Anyway yeah just throwing out ideas that's all.  Appreciate your efforts.
