### ISSUE TITLE
Right-click does not restore border if removed with ontop button

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#110]
1. Load a file with mpv border **enabled**
2. Left-click the pin button (window is pinned and border removed)
3. Right-click the pin button (window is unpinned but border does not come back)

Function needs additional code to address that?

```lua
ne.eventresponder["mbtn_right_up"] = function () mp.commandv("cycle", "ontop") end
```

**Comment by Samillion** [comment]
This is unfortunately a limitation of mpv's implementation for the property ontop. It can only be a toggle, it cannot be explicitly set to true/false.

https://mpv.io/manual/master/#options-ontop

Maybe I'm wrong and there is a way to control the behavior, if there is, please let me know.
