### ISSUE TITLE
CLI returns "[modernz] Command 'escape-ass' not found" and no title on OSC or window bar

### ISSUE THREAD

**Issue by Trickyni-V56** [Samillion/ModernZ#120]
As the title says. I've messed around with both the modernz.conf and the mpv.conf files, but nothing I did made a difference.
digging through the code, I've found  what I assume to be the relevant section around line 1397, but that's the extent of my capability.
mpv seems to still be handling displaying the filename. clicking on the 'mpv' default title does make it display the name of the file it is playing.
<img width="921" alt="image" src="https://github.com/user-attachments/assets/2b18e5f3-2315-4b49-adb2-67eb7f2aa24b">
and here's what my CLI returns:
![image](https://github.com/user-attachments/assets/35cb6f54-7f1b-45ed-a7ca-b805d9968d38)

**Comment by Samillion** [comment]
It's referring to this:
https://github.com/Samillion/ModernZ/blob/89df4efc780fc1924c586ae69a6e9e90afb21125/modernz.lua#L1741-L1750

Which uses this: https://mpv.io/manual/master/#command-interface-escape-ass

If I may ask, what mpv version are you using?

**Comment by Samillion** [comment]
and this is the PR on mpv side of when the command was merged (~7 months ago)
https://github.com/mpv-player/mpv/pull/10149

You just need to update mpv.

**Comment by Trickyni-V56** [comment]
> If I may ask, what mpv version are you using?
as it turns out- 0.37 on mint. 

I think this situation is clear then. Thank you for the quick reply!

**Comment by Samillion** [comment]
My pleasure. I highly recommend updating, especially nowadays. If you follow the recent updates, many fixes and improvements are being added to the backend (especially to gpu-next)
