### ISSUE TITLE
Should the current chapter title be shown next to timestamp? (if available)

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#121]
To mimic online players, would this behavior be a good addition?

![image](https://github.com/user-attachments/assets/071fd03d-9eb6-473d-810d-34f8ca412f2f)

This is relative to @Keith94 issue at https://github.com/Samillion/ModernZ/issues/95 and @mrfragger issue at https://github.com/Samillion/ModernZ/issues/11

**Comment by Keith94** [comment]
I would definitely use it. It uses up the empty space effectively but still looks clean.

Would it replace other chapter texts that are currently implemented like the ones in title, tooltip or thumbnail etc.?

Can it be programmed to launch select.lua to show chapters list?

**Comment by Samillion** [comment]
> Would it replace other chapter texts that are currently implemented like the ones in title, tooltip or thumbnail etc.?

Not a replacement, simply addition for "at a glance" info.

> Can it be programmed to launch select.lua to show chapters list?

At the moment: left click = select menu, right click = simple show chapters list

**Comment by Keith94** [comment]
I think it's a good option to have for sure. So it would follow the same chapter_fmt value as well?

**Comment by Samillion** [comment]
Should be functional here: https://github.com/Samillion/ModernZ/blob/dev_chapter_title_stamp/modernz.lua

Let me know if anything's wrong.

New options:
```ini
# color of chapter title next to left timestamp under seekbar
chapter_title_color=#FFFFFF
# show chapter title next to left timestamp
show_chapter_title=yes
```

**Comment by Samillion** [comment]
I haven't added the following because I'm not sure: (but I coded it lol)
- Should I include the `>` indicator?
- Should it countdown time to next chapter after the title? `[MM:SS]`

![image](https://github.com/user-attachments/assets/c57d6b53-1e6e-4927-8953-6d31bf5a14fa)

@Xurdejl Sorry for the bother, would love your input on this as well.

**Comment by Samillion** [comment]
Updated the script so you guys can see it in action, the layout is:

![image](https://github.com/user-attachments/assets/391f45e5-0e68-4a77-942b-7f05063f6ac3)

**Comment by Keith94** [comment]
For a separator between the time what about using an interpunct - https://www.compart.com/en/unicode/U+00B7

Imo the countdown makes it look a bit busy, might be overkill. Could make it optional.

**Comment by Xurdejl** [comment]
> * Should it countdown to next chapter after the title? `[-MM:SS]`

Personally, I wouldn’t add the countdown.
<br>

> For a separator between the time what about using an interpunct - [compart.com/en/unicode/U+00B7](https://www.compart.com/en/unicode/U+00B7)

I rather like the interpunct as a separator.

**Comment by Keith94** [comment]
One issue on my mind was if I added a separator to `chapter_fmt` for the tooltip, now the hardcoded separator next to timestamp shows up in addition to that

![image](https://github.com/user-attachments/assets/f017d207-2cdd-4eb1-b85b-ccfe2c2f0dab)

On a side note a lot of blurays already have "Chapter" part of the chapter name which can look redundant.

![image](https://github.com/user-attachments/assets/b9ee3f10-dd24-47c0-8cd1-b093f80f17d6)

My solution was to strip the Chapter prefix by default

**Comment by Keith94** [comment]
Customizable mouse bindings? If you think it's worth it.

Based on your screenshot, it looks really nice. Good job

**Comment by Samillion** [comment]
> Customizable mouse bindings? If you think it's worth it.

Oops 😅 I completely forgot about that. Thank you.

**Comment by Xurdejl** [comment]
Looks quite clean. I also checked that YouTube uses a similar Unicode for the chapter's separator: `•` U+2022.

**Comment by Keith94** [comment]
@Xurdejl nice find. More minimal and better looking than the one I linked.

**Comment by Samillion** [comment]
Indeed, that is a great find. I've replaced the old separator with it.

**Comment by Samillion** [comment]
Closed with https://github.com/Samillion/ModernZ/pull/125
