### ISSUE TITLE
Gray out playlist button if there's no playlist?

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#129]
Just an idea to throw out there similar to #109 

If there's only one (current) file in the playlist, the playlist button could be grayed out to avoid confusion about there being something else in the playlist.

This would follow the same logic as the next/previous file buttons: they're gray when there's no additional files, but they're white if there's another file in the corresponding playlist direction.

**Comment by Samillion** [comment]
Good idea! Should it gray out or not show at all?

**Comment by Keith94** [comment]
Hmm maybe hiding is better, to avoid clutter.

I don't think `autocreate-playlist` can dynamically detect when new files are added to a folder, right? So there wouldn't be a case where the button would be needed again

**Comment by Samillion** [comment]
> I don't think `autocreate-playlist` can dynamically detect when new files are added to a folder, right? 

Unfortunately, no. https://github.com/mpv-player/mpv/issues/15061#issuecomment-2438324312

But who knows, maybe it will in the future, since it's a relatively new native feature (starting in 0.39)

**Comment by Keith94** [comment]
Haha damn, devs don't sound too willing or interested in adding it..

I could've sworn you could drag and drop a file onto the player to add it to the current playlist, but that did not happen for me. Or was that only for web videos. Can't remember atm.

**Comment by Samillion** [comment]
Yeah. There are ways to append the playlist with new files/videos/URLs, but nothing as seamless or automated, yet.

I have high hopes though, there are a lot of UX improvements happening lately, so it might be added at one point.

At the moment, libplacebo is taking most of the focus to [deprecate vo=gpu in favor of vo=gpu-next](https://github.com/mpv-player/mpv/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Make+vo%3Dgpu-next+the+default+and+deprecate+vo%3Dgpu%22) (milestone v0.40+).

**Comment by Keith94** [comment]
Ahh okay. So the playlist button will have to pop up again if something was appended. I guess that wouldn't be so bad? Kinda like the download button behavior. It goes away whenever it's useless.

> At the moment, libplacebo is taking most of the focus to deprecate vo=gpu in favor of vo=gpu-next (milestone v0.40+).

It's about time though since gpu-next was my default for quite a long time now lol.
