### ISSUE TITLE
Title only shows "mpv"

### ISSUE THREAD

**Issue by NikunjKhangwal** [Samillion/ModernZ#131]
Hey! Sorry to bother you but I'm quite new to this. I copied your lua and conf file to specified directories and the controller itself is working. However the title only shows "mpv" for every video. I tried changing title to {filename} but no luck. I'm on Linux and here's my mpv.conf:

osc=no
sub-auto=all
geometry=55%x55%
hwdec=auto
show-chapters=yes
screenshot-directory=~/Pictures/mpv
screenshot-format=jpg
screenshot-jpg-quality=90
slang=en #Default Subtitle Langauge

![Screenshot_20241030_164920](https://github.com/user-attachments/assets/30b07cec-77ab-4906-a5d9-e8e13af198b9)

Do you know what's causing it?

**Comment by Samillion** [comment]
Could you show me your `modernz.conf` content, please?

**Comment by NikunjKhangwal** [comment]
I just copy pasted modernz.conf without any changes with the thought of changing something later and tried mpv without using it as well. Same results

**Comment by Samillion** [comment]
> I just copy pasted modernz.conf without any changes with the thought of changing something later and tried mpv without using it as well. Same results

The content you copy/pasted should be in `mpv.conf`, not `modernz.conf`. Those are options for the mpv player itself.

Another note, the option you have `show-chapters`, doesn't exist in mpv.

This is the [full list of options](https://github.com/Samillion/ModernZ/blob/main/docs/USER_OPTS.md) that can be placed with `modernz.conf`

**Comment by Samillion** [comment]
Oh, I think I know why. This might be the same issue as https://github.com/Samillion/ModernZ/issues/120

Try to update mpv, please.

**Comment by NikunjKhangwal** [comment]
Ah! Makes sense. I thought i was going crazy. My distro will ship the update next week so it should be fine. Thanks for your help.

**Comment by Samillion** [comment]
If I may ask, what distro are you using? Debian? I'm surprised mpv package is taking this long to be updated in so many distros.

I understand for Debian (especially old stable), but this was introduced around ~7 months ago.

**Comment by NikunjKhangwal** [comment]
Tuxedo OS actually but i think they fetch mpv from debian repo so that might be the reason.

**Comment by Samillion** [comment]
Noted, thank you very much. Just wanted to keep track in case others in the future report the same issue.

Thankfully though, this is temporary, as the function `escape-ass` is the only one that is relatively new and would cause such breakage.

**Comment by NikunjKhangwal** [comment]
Turns out actually Ubuntu 24.04 is stuck on mpv 0.37 which is currently my system is based on. Here's a site you might find useful too, it tracks packages across all distro's repo: https://repology.org/project/mpv/versions

**Comment by Samillion** [comment]
Thank you for that. Honestly surprising how many aren't up-to date, some even years behind.

I hope you find a package that is more up-to-date, especially with all the additions to libplacebo and wayland lately. Seems Debian Multimedia keeps it updated regularly. 

https://mpv.io/installation/

**Comment by NikunjKhangwal** [comment]
I try to avoid any extra repo or dependency for system maintainance but thanks. I'll probably try flatpak because it always stays up to date.
