### ISSUE TITLE
Time stamps below seekbar have a weird hit box

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#136]
Parts of the element aren't clickable when your mouse is hovering. It's worse when you have longer timestamps.

https://github.com/user-attachments/assets/dfe397d1-c11a-4896-9e14-241464640129

**Comment by Samillion** [comment]
You're absolutely right, it's fixed to a hitbox of 50 width. Which basically only fits the MM:SS timestamp.

Will fix once I get back home.

**Comment by Samillion** [comment]
Should be fixed here: https://github.com/Samillion/ModernZ/blob/dev_timestamp_hitbox/modernz.lua

Could you test and let me know, please?

**Comment by Keith94** [comment]
Found a bug when using dynamic option; i can't click the zero

![mpv_3aqripUQ6i](https://github.com/user-attachments/assets/3de3ef11-cddc-4d72-8652-5e73025c32b2)

**Comment by Keith94** [comment]
Also some kind of overlapping issue, both are hovered simultaneously

![image](https://github.com/user-attachments/assets/bcaafc47-3d4e-4c62-9752-feed0293b090)

**Comment by Samillion** [comment]
Should be good here (I hope lol): https://github.com/Samillion/ModernZ/blob/dev_timestamp_hitbox/modernz.lua

**Comment by Keith94** [comment]
Separator looks good but https://github.com/Samillion/ModernZ/issues/136#issuecomment-2449528452 still remains

You have to set timetotal=no and hover the remaining time when it's over an hour to see the bug.

**Comment by Samillion** [comment]
Oh, oops. Missed that one. Should be good here: https://github.com/Samillion/ModernZ/blob/dev_timestamp_hitbox/modernz.lua

**Comment by Keith94** [comment]
No worries. You fixed the remaining time, but if you toggle that off, the total time is still bugged in the same way

**Comment by Samillion** [comment]
😆  god damnit, I suck. Ok, this time I'll make sure to test all modes. Sorry about that.

**Comment by Keith94** [comment]
Was my bad because I have remaining time on by default so I thought it was specific to that at first.

**Comment by Samillion** [comment]
Ok, so this calculates hitbox for the right time stamp based on the following states: duration, remaining time, milliseconds
https://github.com/Samillion/ModernZ/blob/dev_timestamp_hitbox/modernz.lua

I think this should be good, but I might have missed a state for the right time stamp. Please let me know.

P.S.
Thank you for testing this, and sorry for it taking so long.

**Comment by Keith94** [comment]
![image](https://github.com/user-attachments/assets/1e2dc591-9749-4381-acaa-bd21684704b4)

It looks too wide here. The hour is stripped but it acts like it's there. for remaining time under an hour when set to dynamic

**Comment by Samillion** [comment]
😱 how?

```diff
-    lo.geometry = {x = osc_geo.w - 25 , y = refY -84, an = 9, w = 50 + (state.tc_ms and 30 or 0) + (state.tc_right_rem and 20 or 0) + ((dur >= 3600 and not state.tc_right_rem) and 23 or 0), h = 20}
+    lo.geometry = {x = osc_geo.w - 25 , y = refY -84, an = 9, w = 42 + (state.tc_ms and 30 or 0) + (state.tc_right_rem and 25 or 0) + ((dur >= 3600 and not state.tc_right_rem) and 25 or 0), h = 20}
```

**Comment by Keith94** [comment]
Because on the left side it's even more broken in these scenarios

![mpv_YvM323EJtH](https://github.com/user-attachments/assets/97ac4a0d-7282-4ec4-b8cb-ba2a322b6b9c)

![mpv_6Ryr3s1ksb](https://github.com/user-attachments/assets/a2d46efa-1bb1-46e5-8d5c-9c3edb71a6de)

**Comment by Keith94** [comment]
On the right it hasn't really changed the wide hitbox

![image](https://github.com/user-attachments/assets/f7303d31-18af-4919-b7f7-c7fe4c114ab8)

**Comment by Samillion** [comment]
> Because on the left side it's even more broken in these scenarios

I didn't touch the left time stamp, must have been broken already. 

Only adjusted right time stamp. see commits:
- https://github.com/Samillion/ModernZ/commit/1cbee018a0b44a3cd8428efa773231941a984eb4
- https://github.com/Samillion/ModernZ/commit/0e48d8c98d3fc8ddf452562e50275b67da1a7e91
- https://github.com/Samillion/ModernZ/commit/b3f35d1f9b24244ef31f6c5ad350343dd32976e2
- https://github.com/Samillion/ModernZ/commit/7cc480d25b447eccb98ab6fe4ae537c647328e5d

**Comment by Keith94** [comment]
Ahh my apologies. I forgot to check the commits. But the right side seemed pretty much the same.

**Comment by Samillion** [comment]
My brain shutdown a few times lol. I think this should be better for both left and right timestamps now:
https://github.com/Samillion/ModernZ/blob/dev_timestamp_hitbox/modernz.lua

**Comment by Samillion** [comment]
Synced it to main, so that testing would include the latest changes.

**Comment by Samillion** [comment]
Updated: https://github.com/Samillion/ModernZ/blob/dev_timestamp_hitbox/modernz.lua

Simplified logic to account for hours state in both timestamps.

**Comment by Keith94** [comment]
Thanks, I'll test it as soon as I'm home.

**Comment by Keith94** [comment]
I'm happy to report it looks all fixed now (yay!)
