### ISSUE TITLE
Volume bar when over 100%

### ISSUE THREAD

**Issue by Anthonyy232** [Samillion/ModernZ#147]
Hi, is there any chance of a setting to enable a volume bar when it goes above 100%/100? 0-100 works perfectly because there is the volume indicator, but above 100%, there is no visual cue of where the volume is currently as the bar is already maxed out.

Another possibility is to have another color overlay the first one. For example, if my volume slider is white when on, then 110% would be fully white, and then 10% of the start is (ex:) green. I imagine it would cap out at 200% or whatever the max is

**Comment by Samillion** [comment]
Hmmm. Good point.

What do you think about the volume slider respecting `mpv.conf`?

For example: `mpv.conf`
```
# set max volume level
volume-max=150
```

Reference:
https://mpv.io/manual/master/#options-volume-max

**Comment by Samillion** [comment]
Additionally, I can prepend `osd-msg` to show the volume percentage.

**Comment by Anthonyy232** [comment]
Good with me
