### ISSUE TITLE
Seekbar cache visual indication

### ISSUE THREAD

**Issue by ctlaltdefeat** [Samillion/ModernZ#148]
By default, `seekbarfg_color` determines both progress (coloring everything before the handle) and cache, meaning that one cannot visually distinguish between cached and non-cached segments before the handle.

This is fine for local content and more closely aligns with the UX of many video players. but it's inconvenient for non-local content.
For myself, I've commented out https://github.com/Samillion/ModernZ/blob/main/modernz.lua#L918, which leads to this:
![image](https://github.com/user-attachments/assets/a4085e69-0488-4efb-a499-4dbda6fc2b76)

but I think it would be cool to have that be configurable, perhaps as a different color setting?

**Comment by Samillion** [comment]
Thank you very much for the report, I honestly never thought about that because I rarely play non-local on mpv. Also thanks to @Commander07 for the PR that fixes this issue.
