### ISSUE TITLE
Buttons react inconsistently on mouse clicks

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#153]
For example, this is the behavior I'm seeing for different buttons:

- **Audio and subtitle**: mouse down does nothing until mouse button released
- **Chapter title**: mouse down opens select menu immediately
- **Playlist/file skip**: mouse down does nothing until released
- **Chapter skip**: mouse down skips to next chapter immediately

In my opinion all actions (except for seekbar and volume bar) should only trigger on a mouse up event in case of accidental clicks

A side effect of opening the select menu on mouse down is when you move the mouse while held, the osc pops up over the select menu

https://github.com/user-attachments/assets/5052f411-dfb5-4c9c-b72d-1c02534ecbf1

**Comment by Samillion** [comment]
Good point. Thank you very much for the report, will fix.

**Comment by Keith94** [comment]
Awesome, thanks. :)

**Comment by Keith94** [comment]
I guess it will also have to take into account whether softrepeat options are enabled, too?

`chapter_softrepeat=no` = chapter button only activates on mouse up
`chapter_softrepeat=yes` = chapter button activates and repeats on mouse down

**Comment by Samillion** [comment]
I hate to ask, but may I ask you to confirm something please? Having the press mode changed from down to up, does it generate any errors for you on the laptop touchpad?

**Comment by Keith94** [comment]
Yeah, sadly it does produce errors like before.

Line 1970 `ne.eventresponder["mbtn_left_up"]` crashes the osc with touchpad

**Comment by Samillion** [comment]
> Edit: softrepeat off still works fine though.

So the only scenario where it crashes is with the `softrepeat=true` on chapter skip? All the other `_up` doesn't crash?

`softrepeat=true` with jump buttons and `_up` doesn't crash? The rest of the buttons/title as well?

**Comment by Keith94** [comment]
It crashes with **both** jump and chapter set to `_up` on these lines (with softrepeat enabled):

```lua
ne.eventresponder["mbtn_left_up"] = function () mp.commandv("seek", jumpamount, jumpmode) end
ne.eventresponder["mbtn_left_up"] = function () mp.commandv("seek", -jumpamount, jumpmode) end
ne.eventresponder["mbtn_left_up"] = command_callback(user_opts.chapter_prev_mbtn_left_command)
ne.eventresponder["mbtn_left_up"] = command_callback(user_opts.chapter_next_mbtn_left_command)
```

**Comment by Samillion** [comment]
Last question, I promise. Does it crash on stock OSC? 

I only make these requests because I'm unable to re-produce, if you remember I tried to use Logitech K400's pad, but it didn't crash, so it doesn't simulate the behavior.

**Comment by Keith94** [comment]
>Last question, I promise

No problem, I don't mind 😄 

Here's what I found on stock OSC:

- When I tap on chapter skip, it only skips one chapter at a time (no double skips). It does not crash.
- However, when I click and hold on the chapter button, the player doesn't trigger softrepeat.

I couldn't see anything in mpv documentation regarding softrepeat. So it's just modernZ that implements this?

**Comment by Samillion** [comment]
That's the idea of `softrepeat` in the first place, which is kind of surprising to me that it's only working like that on ModernZ. Why is it there in the other OSCs then? Weird.

So, the issue is with the `softrepeat` code, not the `_up` state. I shall check it out.

**Comment by Keith94** [comment]
>Why is it there in the other OSCs then?

Yeah that is really confusing me now because it makes me wonder: was it working properly at one point when they added it? Why doesn't it work now? Or did they remove the behavior because of the bug I'm experiencing?

I have so many questions 😭

**Comment by Samillion** [comment]
The logic in this needs to be improved to avoid the crash with `_up`
https://github.com/Samillion/ModernZ/blob/e62aeb9f74c40814e8ab5767e5695bf17da35a5a/modernz.lua#L900-L905

I haven't done anything yet, I'm in bed because it's cozy and nice and Mob Psycho II. Soon though. 😆

**Comment by Keith94** [comment]
Here's an interesting find

- In cyl0 fork the touchpad doesn't do any double tap even with softrepeat enabled!
- In zydezu's repo, the double tap issue was introduced there

And one more thing you can try

1. Install cyl0's modernx repo
2. Goto line 2719 and change down to up `    ne.eventresponder['mbtn_left_up'] =`
3. Click and hold on chapter next button

osc will crash even with my regular mouse

**Comment by Samillion** [comment]
It's working as intended, to be honest. I still have no idea why it isn't working in stock or some of the other OSCs.

In fact, the code is identical to stock OSC, which is making me head scratch. I'll have to look over all `eventresponder` to make sure.

The crash happens because the handler is specifically made for the `_down` state.

**Comment by Keith94** [comment]
I went back and tested really old version from 2016 `mpv-x86_64-20160229`: https://www.videohelp.com/software/mpv-media-player/old-versions

What's interesting is that the chapter softrepeat actually works properly there!

First time I've seen that UI, too.

![image](https://github.com/user-attachments/assets/7740ffdc-dbe8-4d04-9bd0-546d3ba28cce)

**Comment by Samillion** [comment]
That's the box stock layout, still available if you switch to it in `osc.conf`.

That is some batman level investigation though, damn lol. Very nice.

**Comment by Keith94** [comment]
Ok well that just led me to discover something else: yes, the double tap happens with stock osc if you use the box layout.

The >> acts like a jump button in that case, so tapping it jumps 20 seconds with one tap, but regular click jumps 10 seconds.

**Comment by Keith94** [comment]
This commit https://github.com/zydezu/ModernX/commit/a2e489ae63dc26d7023a987beab128b427c0db6f helped me realize that my issue is related to `tick_delay` option.

Using a value of `0.03` and the double tap seems solved.

**Comment by Samillion** [comment]
Nice find. So the fastest (lowest) tick value that doesn't cause trouble for you is `0.03`?

**Comment by Keith94** [comment]
I can use `tick_delay=0.024` with seemingly no issue but once I change it to `0.023` it starts happening.

Still not really sure what this all means or if it's useful info, Just thought I'd mention it.

**Comment by Samillion** [comment]
Definitely useful. Think of tick delay as "refresh" in a browser. How fast it refreshes to check change (ie: slider position, play state...etc).

**Comment by Samillion** [comment]
Ok, before doing any deep change, since we covered a lot of stuff. I'll go back to your original post.

Would changing the following to `_up`, while leaving everything else as is, introduce consistency?

> - Audio and subtitle: mouse down does nothing until mouse button released
> - Chapter title: mouse down opens select menu immediately
> - Playlist/file skip: mouse down does nothing until released

**Comment by Keith94** [comment]
Actually no, these would need to be changed to "up" instead of "down" to keep it all consistent:

- Chapter title button
- Chapter skip back
- Chapter skip forward
- Jump back
- Jump forward

**Comment by Samillion** [comment]
Sorry, I misspoke. I didn't mean to consistency as in changing the buttons to `_up` collectively.

I meant as a use case (UX). The original point of changing to `_up` is to avoid accidental clicks. With chapter skip and jump, this is already possible by their counterpart. (ie: undo accidental skip forward, but skipping backwards)

While accidental clicks on `title`, `chapter_title` and `playlist` button is more of a chore/annoyance on accidental click.

Unless I misunderstood the issue, then I apologize.

**Comment by Samillion** [comment]
Sorry again, I gave a partial answer.

So, accidental clicks that would benefit from `_up` switch:
- title
- chapter_title
- playlist
- subtitle track
- audio track
- volume icon (right click) [select audio device]

In essence, all the `select` functions.

Right?

**Comment by Keith94** [comment]
>In essence, all the select functions.

Yes, but from what I can tell most of `select` bindings already do that, except these would need to be adjusted:
- chapter_title => mbtn_left_up
- chapter_backward => mbtn_right_up
- chapter_forward => mbtn_right_up

---

I originally wanted these to be changed (for consistency with other buttons for example fullscreen toggle, showinfo):

- chapter_backward => mbtn_left_up
- chapter_forward => mbtn_left_up
- jump_backward => mbtn_left_up
- jump_forward => mbtn_left_up

but you said:
>the handler is specifically made for the _down state.

So does that mean those 4 above could not be adjusted for the _up state as well?

**Comment by Samillion** [comment]
They can if I adjust the code to work with both `_down` and `_up`, or switch it to `_up`. The difference being do they need to be changed, you know?

I absolutely agree that the select functions should be switched to `_up` to prevent accidental clicks.

These four:
```
chapter_backward => mbtn_left_up
chapter_forward => mbtn_left_up
jump_backward => mbtn_left_up
jump_forward => mbtn_left_up
```

Their counterpart act as a literal undo, so it feels like a code change would be just to match the others, not actual improvement.

Sorry if my comment is confusing, I'm terrible with wording and descriptions. 😅

**Comment by Keith94** [comment]
That's true. I get what you mean. They can be left as is.
