### ISSUE TITLE
Add configurable raisesubswithosc margin

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#16]
Because I have OSC title disabled, the subs get raised too much. See https://github.com/zydezu/ModernX/commit/86f595ebcd10651274d707e159cef24dfc7455cd

**Comment by Keith94** [comment]
Thanks !!

**Comment by Keith94** [comment]
Off topic, but do you think it's better to have `title=${media-title/no-ext}` by default, or keep it the way it is? Looks cleaner without extension but don't know if it's better left untouched.

**Comment by Samillion** [comment]
Agreed, that is what I use in my `modernz.conf` as well.

I'll add it in the next update, kind of reminds me to explain it because in the description it states "media-title" or "filename" implying those are the only two options.

**Comment by Samillion** [comment]
Done.

**Comment by Keith94** [comment]
Looking good. 👍🏻
