### ISSUE TITLE
mpv.exe without file shows empty screen without osc

### ISSUE THREAD

**Issue by herbrot** [Samillion/ModernZ#17]
when exec mpv.exe without file shows empty screen without osd

welcome message seems not to be defined:
[   0.188][f][modernz] Lua error: .../@test/__Move/@x/mpv/portable_config/scripts/modernz.lua:2545: attempt to index upvalue 'texts' (a nil value)

**Comment by Samillion** [comment]
That was a big oopsie on my part caused by https://github.com/Samillion/ModernZ/commit/b06af64d76e1b50cfa29bbf2bbd7faeca7c4c679  I didn't address for all states. Should be good now.

Thank you very much for catching and reporting it early.

**Comment by herbrot** [comment]
perfect

thanks
