### ISSUE TITLE
[modern-image] Zoom in/out button(s) [image viewer mode]

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#171]
Since now ModernZ has a native Image Viewer mode with a simple layout, adding a zoom in/out button(s) would make sense.

**How should I add the zoom in/out button?**
- Two buttons, one for in one for out?
- One button with multi-function?

Also, leaving this here to be included in docs later. A useful auto-profile for ModernZ Image Viewer mode, in `mpv.conf`:
```ini
reset-on-next-file=video-rotate,video-zoom,panscan,video-unscaled,video-align-x,video-align-y

[Image-Viewer]
    profile-desc=Settings for Image Viewer mode with ModernZ osc
    profile-cond=p["current-tracks/video"] and p["current-tracks/video"].image and not p["current-tracks/video"].albumart
    prefetch-playlist=yes
    stop-screensaver=no
    title=${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename}} [${?width:${width}x${height}}]
    script-opts-append=modernz-windowcontrols_title=${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename}} [${?width:${width}x${height}}]
    script-opts-append=modernz-window_title=yes
    script-opts-append=modernz-fade_alpha=100
    script-opts-append=modernz-bottomhover_zone=100
```

![image](https://github.com/user-attachments/assets/dec39e5c-578d-4c44-a294-d061907417df)

Pinging: @Commander07 @Keith94 @Xurdejl

**Comment by Keith94** [comment]
One button would probably work IMO.

Left click => zoom in
Right click => zoom out
Wheel_up => zoom in
Wheel_down => zoom out
mbtn_mid => reset zoom

**Comment by Commander07** [comment]
I agree with Keith when it comes to a zoom _button_. However i feel zooming should be entirely mouse based i.e zoom with mouse wheel onto the pointer. Mouse based zoom is much more intuitive. However if a zoom element were to be added then my personal preference would be a slider like in Windows Photos.
![image](https://github.com/user-attachments/assets/ae558400-363b-4922-99c1-b475d7493240)

**Comment by Samillion** [comment]
I love the slider idea. I'll implement it exactly like the picture you showed.

Also, I was talking to guidocella earlier, and he has a wonderful [mpv-image-conf](https://github.com/guidocella/mpv-image-config), which I'll link to in the `Image Viewer Mode` docs page, so that users can turn mpv into a full fledged image viewer.

For example, allowing mouse centric zoom:
```
# Zoom towards where the cursor is hovering.
WHEEL_UP   {image} script-message cursor-centric-zoom .1
WHEEL_DOWN {image} script-message cursor-centric-zoom -.1
```

**Comment by Samillion** [comment]
https://github.com/user-attachments/assets/38a0c76a-61ab-4bab-b452-e51c6fcce39b

**Comment by Samillion** [comment]
**Script to test:** [modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_modernimage_zoomcontrols/modernz.lua)

**Changes:**
- Added zoom controls as suggested
- Removed title completely to keep a minimal look
- Corrected offset

**To do:**
- Add language phrases to locale `Zoom In`, `Zoom Out`

**Comment by Keith94** [comment]
Looks awesome. The zoom handle's position wasn't updating in real time when you drag it, though.

**Comment by Samillion** [comment]
True! Nice catch.

**Comment by Samillion** [comment]
Should be fixed now. (same test script)

**Comment by Keith94** [comment]
Maybe can increase the video-zoom cap to 4? Photos apps goes up to 800% which looks like the equivalent of ~3.8 in mpv.

Photos app slider can also do <100% values, if that's wanted.

**Comment by Commander07** [comment]
Perhaps the max/min zoom should be configurable.

**Comment by Keith94** [comment]
@Commander07 agreed, good idea.

**Comment by guidocella** [comment]
>     title=${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename}} [${?width:${width}x${height}}]
>     script-opts-append=modernz-windowcontrols_title=${?demuxer-via-network==yes:${media-title}}${?demuxer-via-network==no:${filename}} [${?width:${width}x${height}}]

What is the point of not always printing `media-title`? Image files don't usually have a title which makes `media-title` fallback to `filename` anway.

**Comment by Samillion** [comment]
**Test script:** [modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_modernimage_zoomcontrols/modernz.lua)

**Changes:** https://github.com/Samillion/ModernZ/commit/14a1ec524f92731fff2ae3f04c01a5bd98bfef11
- Add options for zoom min/max levels
- Set default zoom max to `4`, minimum to `-1`
- Scroll wheel to work on zoom icons, not just slider
- Right click on slider also resets zoom level to `0`
- Change language label `texts` to `locale`
- Added locale phrase for `Zoom In` and `Zoom Out`

Suggested in `mpv.conf`:
```ini
reset-on-next-file=video-rotate,video-zoom,panscan,video-unscaled,video-align-x,video-align-y

[Image-Viewer]
    profile-desc=Settings for Image Viewer mode with ModernZ osc
    profile-cond=p["current-tracks/video"] and p["current-tracks/video"].image and not p["current-tracks/video"].albumart
    prefetch-playlist=yes
    stop-screensaver=no
    title=${media-title} [${?width:${width}x${height}}]
    script-opts-append=modernz-windowcontrols_title=${media-title} [${?width:${width}x${height}}]
    script-opts-append=modernz-window_title=yes
    script-opts-append=modernz-fade_alpha=100
    script-opts-append=modernz-bottomhover_zone=100
```

**Comment by Keith94** [comment]
Thanks for implementing the changes. `script-opt` is also an alias of `script-opts-append` but it only works on newer builds I think.

**Comment by Samillion** [comment]
🎉 https://github.com/Samillion/ModernZ/blob/main/docs/IMAGE_VIEWER.md
