### ISSUE TITLE
Add option to adjust seekbar height

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#179]
Anybody know if changing the height breaks anything?

https://github.com/Samillion/ModernZ/blob/d448a5b1646a6d4461095e1a994f28b744ca02b3/modernz.lua#L1612

**Comment by Samillion** [comment]
Doable for sure. We'd need to account for handle size as well.

This is tempting me now. Instead of a constant circle seek handle, why not have option for a rectangle handle?

Keith, you are like a devil tempter. 😆

**Comment by Keith94** [comment]
>We'd need to account for handle size as well.

True, I thought handle size capped at 1 seemed a little low but meh.

>why not have option for a rectangle handle?

That would be fun to play around with or even triangle. Though I think circle will be the best option for most people.

**Comment by Samillion** [comment]
Also, the slider handle radius adapts automatically which makes customizing this so much more easier. Completely forgot about that.

https://github.com/Samillion/ModernZ/blob/07cc4c727012a622cf3152ab9c650a26d956bf2a/modernz.lua#L892

In essence, you need to balance height for `seekbarbg` and `seekbar` elements.

The pic I posted is:
```lua
    lo = add_layout("seekbarbg")
    lo.geometry = {x = refX , y = refY - 100, an = 5, w = osc_geo.w - 50, h = 5}
```

and:
```lua
    lo = add_layout("seekbar")
    lo.geometry = {x = refX, y = refY - 100, an = 5, w = osc_geo.w - 50, h = 20}
```

- **Old heights:** 2, 16
- **New heights:** 5, 20

Should I make those heights configurable in user options?

Also, should I apply the thicc boy changes? 😆

**Comment by Samillion** [comment]
The size difference between the two is due to `\blur` and `\bord` values

```lua
seekbar_bg = "{\\blur0\\bord0\\1c&H" .. osc_color_convert(user_opts.seekbarbg_color) .. "&}",
seekbar_fg = "{\\blur1\\bord1\\1c&H" .. osc_color_convert(user_opts.seekbarfg_color) .. "&}",
```

**Comment by Xurdejl** [comment]
> Should I make those heights configurable in user options?

It depends. (not about this option, but in general) It’s worth keeping in mind that adding too many options can make the code more complex and might overwhelm users, but if it’s something that will actually be used, then sure.

**Comment by Samillion** [comment]
> It depends. (not about this option, but in general) It’s worth keeping in mind that adding too many options can make the code more complex and might overwhelm users, but if it’s something that will actually be used, then sure.

I honestly agree, even maintaining wise (https://github.com/Samillion/ModernZ/commit/395f8242434165fedfb13c3bd7fa996b3e3603d0), it's easy to forget adding options because they're so many already.

How about we just adjust the default values to be a bit thicker, without adding any new options.

Does this look better? (seekbar and volume)

![image](https://github.com/user-attachments/assets/cbc49b00-1a55-4500-a75d-6e9752c4dafc)

**Comment by Keith94** [comment]
Looks great! Merge it like that and close this one out 😄

**Comment by Samillion** [comment]
I hate to be a bother, but can you confirm that it looks well on your ends as well?
https://github.com/Samillion/ModernZ/blob/dev_sliders_thicc/modernz.lua

Just want to make sure before merging into main. I've had many scenarios that work for me, but not others. 😅

**Comment by Keith94** [comment]
Me wonders if the chapter markers should be raised or something since they get covered by the handle now

![image](https://github.com/user-attachments/assets/f98af9b9-291e-4675-b195-9b8ebadb5e05)

**Comment by Samillion** [comment]
Hmm? Same as before
![image](https://github.com/user-attachments/assets/7b9e37cb-9729-4324-b35b-a8859b6a9f9f)

**Comment by Keith94** [comment]
Ahh you're right, nevermind. Thought it looked different.

**Comment by Keith94** [comment]
I did not expect negative values of `seekbarhandlesize=` to look like that. Hidden easter egg perhaps lol.

![image](https://github.com/user-attachments/assets/3f7513f1-1780-42fb-9684-16e47b937639)
