### ISSUE TITLE
Changing vid scale causes long freezes when minimizing

### ISSUE THREAD

**Issue by redsigma** [Samillion/ModernZ#183]
I noticed that  if i use `vidscale=no` and sometimes i constantly minmize and restore, the window freezes for like 1-5 seconds and sometimes it recovers.

I noticed that if i hardcode the `display_h` variable from  `osc_init()` function, then the issue disappears.

I am not really sure what is going on. But for some context I was trying to add a feature to `auto pause the video on minimize` and `auto unpause the video when restored`

**Comment by Samillion** [comment]
> I am not really sure what is going on. But for some context I was trying to add a feature to auto pause the video on minimize and auto unpause the video when restored

How were you implementing it? By editing `modernz.lua`? That could be the reason.

There is a simpler way to achieve what you want, by using auto profiles in `mpv.conf`. 

For example, try this:
```ini
[Minimized] 
    profile-desc=Pause when minimized
    profile-cond=window_minimized and vid and not p["current-tracks/video/albumart"]
    profile-restore=copy-equal 
    pause
```

**Comment by redsigma** [comment]
> > I am not really sure what is going on. But for some context I was trying to add a feature to auto pause the video on minimize and auto unpause the video when restored
> 
> How were you implementing it? By editing `modernz.lua`? That could be the reason.
> 
> There is a simpler way to achieve what you want, by using auto profiles in `mpv.conf`.
> 
> For example, try this:
> 
> ```ini
> [Minimized] 
>     profile-desc=Pause when minimized
>     profile-cond=window_minimized and vid and not p["current-tracks/video/albumart"]
>     profile-restore=copy-equal 
>     pause
> ```

will check that out. This is the code that i added btw. 

![image](https://github.com/user-attachments/assets/60e7c0b9-eeab-4844-b38a-0e3e1e689dc0)


I belive that issue happens with a fresh .lua file too but let me double check.

**Comment by Samillion** [comment]
This will handle it on osc level, which should be fine for the most place, but it definitely won't be faster than letting mpv handle it.

Try the auto profile I posted instead, and let me know. I'm very curious about it.

**Comment by redsigma** [comment]
Just pasted that in the mpv.conf  and also reverted all changes in the .lua file

The issue happens every time I minimize and restore. But this time it always recovers after 1-2 seconds, instead of perma freezing.

Below is the video I was testing.

https://github.com/user-attachments/assets/9022ee41-7de4-4631-be36-dbb0a69495b5

**Comment by Samillion** [comment]
Noted. Thank you very much. Could you please post a log to help me track the issue?

Try to reproduce the behavior so it shows in the log, please.

```
mpv sample-4.mp4 --v --log-file=output.txt
```

**Comment by Samillion** [comment]
One last question, does it happen with mpv's stock osc or just ModernZ?

**Comment by redsigma** [comment]
I think i forgot an important part. Im using this instead of raw mpv

https://github.com/tsl0922/ImPlay

I removed modernZ and tried the stoc OSC from that   +  that profile in the mpv.  And it works without issues.

**Comment by Samillion** [comment]
It uses libmpv as far as I know, I think you should be able to produce a log file if you include `log-file=output.txt` in your `mpv.conf`

Or maybe it has a native log generating feature.

**Comment by redsigma** [comment]
Ok good news.  I tried with latest `mpv` and fresh install of this plugin  + those lines in the mpv.conf

And the issue doesn't happen.  So I believe ImPlay uses an outdated mpv .

**Comment by redsigma** [comment]
I guess, this is a false positive in this case. Any chances you might know a OSC for audio files ?  I am looking for something to replicate VLC media player's playlist .

**Comment by Samillion** [comment]
> Ok good news. I tried with latest mpv and fresh install of this plugin + those lines in the mpv.conf
> 
> And the issue doesn't happen. So I believe ImPlay uses an outdated mpv .

Ah, this seems to be a common occurrence. Was it using mpv 0.37 or less?

> Any chances you might know a OSC for audio files ? I am looking for something to replicate VLC media player's playlist .

I recently added an [image viewer](https://github.com/Samillion/ModernZ/blob/main/docs/IMAGE_VIEWER.md) mode to ModernZ osc. I might add an audio oriented one in the future, but I can't promise anything or a time frame, unfortunately.

ModernZ is basically re-writing the `modern` origin, so we're still fixing and adding many things.

You should try mpv's [User Scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) wiki. If you're looking for something miniminal (UI wise), [mfpbar](https://codeberg.org/NRK/mpv-toolbox/src/branch/master/mfpbar) might be the answer.

**Comment by Samillion** [comment]
Final note, you should ask on ImPlay if it's possible to update the mpv binary manually. I'm not sure how they're using, but most likely you can just place a newer binary in a directory or a newer libmpv

**Comment by Samillion** [comment]
Also, possibly related: https://github.com/tsl0922/ImPlay/issues/27
