### ISSUE TITLE
showonpause behavior varies with frame stepping

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#184]
As per mpv docs

>.
Step forward. Pressing once will pause, every consecutive press will play one frame and then go into pause mode again.
,
Step backward. Pressing once will pause, every consecutive press will play one frame in reverse and then go into pause mode again.

With showonpause=yes, stepping forward shows osc, but stepping backwards doesn't show it.

**Comment by Samillion** [comment]
So you mean `frame-step` or specifically, `frame-back-step`?

Both frame steps pause and show osc for me.

The difference being show osc timeout on pause. It doesn't reset it. Unless you have `keeponpause` as well.

**Comment by Keith94** [comment]
I'll take a more in-depth look soonish in case it was something to do with my config .

**Comment by Keith94** [comment]
I _was_ using keeponpause=no, so I did some more testing around it.

Stepping forward multiple times causes the player to go back and forth between paused and play states, which makes the osc pop up whenever it paused. Whereas stepping backward was keeping the player in paused mode the whole time, so the osc was not showing up.

So should be working as intended. Sorry for the confusion.

**Comment by Samillion** [comment]
No worries at all. If it's not functioning as intended, don't hesitate to re-open this issue or create another one.

You're the official bug zapper of ModernZ. 😄

**Comment by Keith94** [comment]
Lol I try my best, but sometimes act too hastily if I don't have enough time to troubleshoot.

**Comment by Samillion** [comment]
You've witnessed me replying so many times without reading and sometimes even responding about something completely different. Trust me, you're perfectly fine compared to me. 🤣

**Comment by Keith94** [comment]
Haha. Props to you for being so active though. Not every day you see that on here.
