### ISSUE TITLE
Consider: Fully embrace interactive lists

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#19]
At the moment, the Audio, Subtitle and Playlist buttons by default show a simple list that does nothing.

Unless you choose to click them with the "interactive" option. (ie: playlist => right click => interactive playlist).

Now that the latest update for `console/select` has been [merged](https://github.com/mpv-player/mpv/pull/15016) on mpv, the interactive lists work beautifully in `ModernZ OSC` with full mouse support.

Which reminds me, I highly recommend updating `mpv`, `console.lua`, `select.lua` to take advantage of the those latest updates, regardless if `ModernZ OSC` is used or not.

**Changes:**
- `Playlist button`: `Left click` => Interactive Playlist, `Right click` => Simple Playlist
- `Audio button`: `Left click` => Interactive Audio Tracks list, `Right click` => Simple Audio Tracks cycle
- `Subtitle button`: `Left click` => Interactive Subtitles list, `Right click` => Simple subtitles cycle

**Comment by Keith94** [comment]
Having `showonpause` enabled kinda breaks it, because when video is paused the playlist thingy opens behind the OSC. I'll just keep it off for now at least.

**Comment by Samillion** [comment]
Good catch. Noted, easily fixed.

**Comment by Samillion** [comment]
Could you try this version and see if it's fixed in it, please:
https://github.com/Samillion/ModernZ/blob/wc_bug_rewrite/modernz.lua

This is a dev version, if you notice any other bugs other than the already opened issues, please let me know.

**Comment by Keith94** [comment]
Fixed here :)

**Comment by Samillion** [comment]
Awesome. At least  one thing worked. 🤣

**Comment by Samillion** [comment]
I will wait until this [PR](https://github.com/mpv-player/mpv/pull/15101) is merged in mpv, then I will make the full change in ModernZ.

I've already updated the [interactive playlist](https://github.com/Samillion/ModernZ#interactive-playlist) section that showcases this feature.

**Comment by Keith94** [comment]
The current readme says you can use right mouse click for interactive audio/subtitles, but this doesn't work for me yet. It does work for playlists however when right clicking. Are we just waiting on the PR for that?

**Comment by Samillion** [comment]
I updated the text, not the script. 😝 

Just waiting for that PR to get merged before updating the script. Should be a day or so.

**Comment by Keith94** [comment]
>Audio button: Left click => Interactive Audio Tracks list, Right click => Simple Audio Tracks cycle
>Subtitle button: Left click => Interactive Subtitles list, Right click => Simple subtitles cycle

Hi, did you decide against this change? IMO left click for interactive would be good to have, to make it consistent with playlist button. Or if not, how can I make the change in modernz.lua itself

**Comment by Keith94** [comment]
Okay that's great! Works for me. More customization is usually better anyway.
