### ISSUE TITLE
Feature request : A playback speed toggle 

### ISSUE THREAD

**Issue by houssemko** [Samillion/ModernZ#192]
I opened this request before , the feature got implemented into the seek bar , I think that's not the best way to implement it because with a toggle  :
1. the mouse wheel can increase or decrease the playback speed by an increment of 0.25x for example 
1. A left click to increase the playback speed by an incremental 1x
2. and pressing right click should switch back to default 1x playback speed

**Comment by Samillion** [comment]
Noted. Will replace seekbar option with a dedicated speed control button. (disabled by default)

|   Icon    |    Details    |
| -------- | ----------- | 
| <img src="https://github.com/user-attachments/assets/1bff9b20-5517-487a-bea2-8ecf58527874" width="30"> | https://icon-sets.iconify.design/fluent/top-speed-20-regular/ |

**Behavior:**
- Left click: incr 1
- Right click: reset => 1
- Mouse wheel: incr 0.25x up/down

**Comment by houssemko** [comment]
Perfect thank you .
