### ISSUE TITLE
Declutter: Move seek related buttons to seekbar

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#193]
Since speed control button is coming soon https://github.com/Samillion/ModernZ/issues/192

Would it be a good idea to move seek related buttons above the seekbar? To de-clutter the OSC and give focus areas of button functions.

I've seen some players and osc's (ie: uosc) do this, but I'm not actually sure if it's a good idea or not.

Test script: https://github.com/Samillion/ModernZ/blob/dev_osc_declutter_speed/modernz.lua

**Changes:** https://github.com/Samillion/ModernZ/commit/08f386ae087d88a26c1c827f289df16e4604e555
- Add speed control button
- Move speed and loop buttons above seekbar to de-clutter
- Change font size for window title and seekbar title
- Fix long titles being stretched
- Reduce default bottom hover zone to 145 from 160
- Change some label phrasing in locale

**To do:**
- Add shuffle button next to loop button

![speed-declutter](https://github.com/user-attachments/assets/706b383f-0ed4-4f12-b558-c17529f05cd6)

Pinging: @Xurdejl @Commander07 @Keith94 @Anthonyy232 @houssemko

**Comment by Anthonyy232** [comment]
Which one is that? The two on the top right? I don't use those so I'm not entirely sure. If so, it looks fine there -- works for me. Would be great if it is optional just like everything else though :)

**Comment by Samillion** [comment]
> Which one is that? The two on the top right? I don't use those so I'm not entirely sure. If so, it looks fine there -- works for me. Would be great if it is optional just like everything else though :)

Yup, the one above the seekbar on the right. All elements are always optional.

**Comment by Anthonyy232** [comment]
Are there any icons for the speed one? I'm assuming that's the 1.5x, 2.0x stuff. I didn't recognize it at first so it's probably not that intuitive, but I understand if there are no other options as is the case with these things usually

**Comment by Samillion** [comment]
It's not added yet, but this is how I plan to implement it:

|   Icon    |    Unicode    | Bytes       |
| -------- | ----------- | ----------- |
| <img src="https://github.com/user-attachments/assets/1bff9b20-5517-487a-bea2-8ecf58527874" width="30"> | `` | `\239\160\177` |

**Behavior:**
- Left click: +1 (max: 100)
- Right click: reset => 1
- Mouse wheel: +/- 0.25x up/down (max: 100, min: 0.25)

**Comment by Anthonyy232** [comment]
Sorry, I meant to ask if there were any **other** icons. Texting on mobile is difficult haha

**Comment by Samillion** [comment]
The only other one I could find that simulates "speed" is:

<img src="https://github.com/user-attachments/assets/eabd8fc6-202d-4555-b340-6e6a503b824e" width="30">

Full list of available icons:
https://icon-sets.iconify.design/fluent/

**Comment by Anthonyy232** [comment]
Not entirely sure how this would look, for all I know it could be terrible. But how about just showing the current speed? Like 1x for default, and it changed depending on what speed it is at it. Could be useful for knowing what speed it is currently and also I think the x naming scheme is common enough to denote speed. But I think either works!

**Comment by Samillion** [comment]
> This may require an absurd amount of custom icons so in which cese, ignore lol

It would, yeah lol. We'd need to account for every .25 change. Or find an icon that places text within it neatly.

Just text without icon:

![image](https://github.com/user-attachments/assets/4b982c9b-91e2-4ae1-8069-bebede17ab80)

To note though: on speed changes, it displays an OSD message

![image](https://github.com/user-attachments/assets/59c56bb2-c75d-4d69-942d-ae9b82d0f554)

**Comment by Samillion** [comment]
Test script: https://github.com/Samillion/ModernZ/blob/dev_osc_declutter_speed/modernz.lua

Speed control button is active in it, with the seek related buttons positions above the seekbar

![speed-declutter](https://github.com/user-attachments/assets/706b383f-0ed4-4f12-b558-c17529f05cd6)

**Comment by Keith94** [comment]
I don't see any issues with it in a default scenario.

In an unexpected scenario, if user disabled all buttons except for loop for example, it may look kind of silly to move it to the top when you have ample room below seekbar.

Most web players tackle the clutter with an overflow button/menu which is likely out of scope, unless the area above seekbar could act like an overflow when the button "limit" (below seekbar) is reached.

I have a feeling such behavior could be a tad over-complicated, but throwing it out there. Feel free to dismiss lol.

**Comment by Samillion** [comment]
Thank you very much for your inputs, guys. I've adjusted them back to normal.

![image](https://github.com/user-attachments/assets/6bb4286c-e013-4378-aa72-01c337e359f5)

> To give some ideas, this is the Spotify layout using a custom [Spicetify theme](https://github.com/sanoojes/Spicetify-Lucid) based on fluent design. It's common for media players to place the loop and shuffle buttons on each side of the play button, along with the previous and next buttons.

That is a great idea. Thank you for that, this will give us a design route if we ever need to re-organize the whole thing.
