### ISSUE TITLE
Seekbar doesn't follow cursor precisely when handle is zero

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#199]
### mpv Information

```bash
mpv 3bbc770 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  8 2024 09:24:36
libplacebo version: v7.349.0
FFmpeg version: b862792
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Reproduction Steps

1. Set seekbarhandlesize=0
2. Set scalewindowed=2 (not required but helps to see the issue more clearly)
3. Play a file, pause the video, and seek somewhere

### Expected Behavior

Behave like stock osc where seekbar is lined up with cursor when seeking

![brave_4AzPaAIyjO](https://github.com/user-attachments/assets/11173ebf-3293-4367-8212-db71f53fe1fe)

### Actual Behavior

Seekbar position is offset by a few pixels

![image](https://github.com/user-attachments/assets/7b65745a-01c6-4484-a474-5684b86ce967)

### Log File

Shouldn't be needed but correct me if I'm wrong.

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
Terribly sorry about the late response, had an unexpected workload.

Nice catch. Slider handle size breaks on 0 and negative values. I'll validate the option so it checks that it's always higher than `0`, if not, it will set it to `0.1`.

**Comment by Samillion** [comment]
> Log file
> Shouldn't be needed but correct me if I'm wrong.

Good point. I made log file optional instead of required.

**Comment by Keith94** [comment]
Awesome thanks for the fix !!
