### ISSUE TITLE
Buttons stop working intermittently

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#2]
Strange bug, but clicking some of the UI buttons don't do anything.

Seems to happen when you click the jump buttons followed by pause. Don't know if it's specific to laptop trackpads or if that makes a difference, yet.

https://github.com/user-attachments/assets/68686d63-d107-47d8-9419-9fc75da01bec

**Comment by Samillion** [comment]
I updated the script (https://github.com/Samillion/ModernZ/commit/45c24500bf87af954da22b88ec91bc86d8f97293), could you try and see if the issue is fixed please?

**Comment by Keith94** [comment]
I tried it, but the same issue still happens, especially when you click on a lot of different buttons while osc stays visible

**Comment by Keith94** [comment]
It happens with a regular mouse too, and completely stock modernz.conf FWIW.

**Comment by Samillion** [comment]
I'm unable to replicate this problem. I'll try to debug the process as much as I can by disabling each element.

Will get back to you as soon as I find the cause.

**Comment by Samillion** [comment]
Before I go deep, could you try changing the "always" value to "auto" in this:
https://github.com/Samillion/ModernZ/blob/9ae4ce19de1e2c8901323db1a2a43c19f5b85baf/modernz.lua#L3046

As I'm still unable to replicate, just want to eliminate suspects.

**Comment by Keith94** [comment]
Problem persists :(.. It's like the mouse clicks just go right through the osc. For example, double clicking while the jump button is highlighted will toggle fullscreen mode. Thanks for the help troubleshooting

**Comment by Samillion** [comment]
I'll perform a thorough check, very strange. I tried all kinds of scenarios to replicate. Still, this is most likely due to the changes I've made to match mpv's osc.lua (ie: rendering).

https://github.com/user-attachments/assets/a15cd838-b66d-4c34-9251-1aefae3e412e

**Comment by Keith94** [comment]
I changed mpv builds to latest git and it seems resolved now (same with #4)

**Comment by Samillion** [comment]
Ah, phew. That was on my mind. Look at the recent commits, I've went through every bit to try and figure this out. 🤣 

Genuinely glad this was resolved. Don't hesitate to open more issues with ideas or suggestions.
