### ISSUE TITLE
Changing the settings of modernz.conf in script-opts folder doesn't affect the osc settings 

### ISSUE THREAD

**Issue by houssemko** [Samillion/ModernZ#201]
### mpv Information

```bash
mpv v0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  6 2024 17:31:17
libplacebo version: v7.349.0
FFmpeg version: n7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Reproduction Steps

I have the files set up in their correct folders 
I changed the options in modernz.conf 
I keep the modernz.lua unchanged 
Nothing changes in the osc ,
however , changing the options in modernz.lua works

### Expected Behavior

When tweaking the option in modenz.conf the osc should reflect the changes 

### Actual Behavior

No changes happen 

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
Please make sure the configuration file is named `modernz.conf` and is placed inside `script-opts/` folder.

If you're still experiencing the same issue, please provide a log file `--log-file=output.txt`. Attach the log file, don't paste the text, please.

**Comment by houssemko** [comment]
I'm sure about the configuration file .
What steps to do to generate the log file?

**Comment by Samillion** [comment]
`mpv whatever_video.mp4 --log-file=output.txt` or include `log-file=output.txt` in your `mpv.conf`

You can also specify the location of the log file, ie: `--log-file=C:\output.txt`

https://mpv.io/manual/master/#options-log-file

**Comment by houssemko** [comment]
[output.txt](https://github.com/user-attachments/files/17701575/output.txt)
this is the log file with the default modernz.lua , and the configured modernz.conf configuration file

**Comment by Samillion** [comment]
Your log shows that you didn't place `modernz.conf` in `script-opts/`:
```
[   0.044][d][global] config path: 'script-opts/modernz.conf' -/-> '/home/houssem/.config/mpv/script-opts/modernz.conf'
[   0.044][d][global] config path: 'script-opts/modernz.conf' -/-> '/home/houssem/.mpv/script-opts/modernz.conf'
[   0.044][d][global] config path: 'script-opts/modernz.conf' -/-> '/etc/mpv/script-opts/modernz.conf'
[   0.044][d][modernz] script-opts/modernz.conf not found.
```

**Comment by houssemko** [comment]
ow my bad i created the folder as scripts-opts not script-opts
