### ISSUE TITLE
Chapter title over 200 width can't be clicked fully

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#202]
### mpv Information

```bash
mpv 3bbc770 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  8 2024 09:24:36
libplacebo version: v7.349.0
FFmpeg version: b862792
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Reproduction Steps

1. Open https://www.youtube.com/watch?v=uM-fS9bRiAo
2. Go to the chapter at 26:16 **_Ys (Yees) 8: Lacrimosa of Dana (yes, that's what it's actually called)_**
3. Hover the end of the chapter title (button)

### Expected Behavior

Hitbox encompasses the entire title

### Actual Behavior

w = 200 in the code doesn't cover the full title. It supports most cases except really long titles

Maybe that's just a limitation of the feature... the width can't dynamically adjust for the amount of characters in chapter title :(

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
Ah, I can't believe I left it a fixed width, nice find.

Could you please try with this:
https://github.com/Samillion/ModernZ/blob/dev_chaptitle_width_refactor/modernz.lua

**Changes:**
- Base chapter title width on osc width (minus timestamp states), to match main title behavior.

**Comment by Keith94** [comment]
Tested it briefly and it's much better. It uses the full width of the osc now, so it should cover all cases.
