### ISSUE TITLE
About the first chapter in the seekbar

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#204]
### What would you like to discuss?

For example, at the url https://www.youtube.com/watch?v=uM-fS9bRiAo, the chapter starting at 00:00 intro has the two triangles on seekbar

![mpv_W0Jw5TeHPf](https://github.com/user-attachments/assets/3273b5b8-1686-4da7-8c1f-a6b1214198d7)

In stock osc it doesn't show the 00:00 mark, only shows the 00:30 and onwards marks

![lfWsXesfM8](https://github.com/user-attachments/assets/a7f50d18-ac8d-423e-a8b0-a19b477dda9b)

I think it looks a bit redundant displaying the first mark. What do you think? @Samillion

**Comment by Keith94** [comment]
But it borrows mpv's exact code, doesn't it?

```lua
    ne.slider.markerF = function ()
        local duration = mp.get_property_number("duration")
        if duration ~= nil then
            local chapters = mp.get_property_native("chapter-list", {})
            local markers = {}
            for n = 1, #chapters do
                markers[n] = (chapters[n].time / duration * 100)
            end
            return markers
```

Adjusted to `n = 2` removes the first mark but it completely breaks right-clicking on seekbar

**Comment by Samillion** [comment]
> But it borrows mpv's exact code, doesn't it?

Yup, it does. I think it's showing the same marker, but on stock it's more visible due to gap/design difference, right?

> Adjusted to `n = 2` removes the first mark but it completely breaks right-clicking on seekbar

Additionally you need to adjust the index to match, try: (I'm not home, so not tested)
```lua
            for n = 2, #chapters do
                markers[n - 1] = (chapters[n].time / duration * 100)
            end
```

But this makes the first marker always ignored. Markers (or chapters) are set by users, wouldn't that create a discrepancy in many valid chapter files? (ie: where the first marker is placed more efficiently in the timeline)

**Comment by Keith94** [comment]
>on stock it's more visible due to gap/design difference, right?

On stock one it doesn't show the foremost marker at all (YouTube is the same), so that's what made me notice the discrepancy.

>wouldn't that create a discrepancy in many valid chapter files?

So far none that I could tell, but I didn't test any other files yet.

With those changes it still breaks the "right-click to seek to closest chapter" so I assume more changes would be needed..

**Comment by Samillion** [comment]
> With those changes it still breaks the "right-click to seek to closest chapter" so I assume more changes would be needed..

If it's not a bother, what's the error exactly?

**Comment by Keith94** [comment]
Of course no problem haha

```lua
            for n = 2, #chapters do
                markers[n - 1] = (chapters[n].time / duration * 100)
            end
```

This one makes it so right click seeks to the chapter before the nearest one (in a negative direction)
For example right click on this spot seeks to the 00:30 chapter but it should be the one after
![mpv_6i0b1CBP5Z](https://github.com/user-attachments/assets/70a28180-658e-43dc-905a-cc74a71ee3c2)

```lua
            for n = 1, #chapters do
                if n ~= 1 then
                    markers[n] = (chapters[n].time / duration * 100)
                end
            end
```
With this one, right click does nothing at all.

**Comment by Samillion** [comment]
Noted, and thank you very much.

So the markers are better that way, just the behavior needs to be fixed, right?

I'm noting things down so when I'm back home I don't forget lol.

**Comment by Samillion** [comment]
Unrelated question, I like your seekbar colors. Would you mind sharing your seekbar fg, bg, cache colors? I want to test them and possibly turn them into default values.

**Comment by Keith94** [comment]
>So the markers are better that way, just the behavior needs to be fixed, right?

Yeah I think it would be good as long as it doesn't break anything.

>Would you mind sharing your seekbar fg, bg, cache colors? I want to test them and possibly turn them into default values.

Sure! That would actually be pretty cool. Here's what I use.

>seekbarfg_color=#FB8C00
seekbarbg_color=#94754F
seekbar_cache_color=#918F8E

**Comment by Samillion** [comment]
Hmmm. I just checked with stock, it doesn't ignore the first marker:

![osc_lua](https://github.com/user-attachments/assets/cde870be-1a01-46b0-b53a-58e86d581333)

![image](https://github.com/user-attachments/assets/c0459d2c-72d8-4b6b-bc36-0b6660aa8b80)

**Comment by Keith94** [comment]
Damn, really? My bad then for the false report. My PC must be cursed so I'll check again tomorrow.

**Comment by Samillion** [comment]
No, no. This might be a bug of its own. I wonder why the first marker (nibble) is not showing for you on stock. hmm.

This is consistent in all videos with chapters for you?

**Comment by Samillion** [comment]
By the way, absolutely love your colors choice. Definitely switching them to default, they flow more naturally than the choice I've made.

Thank you for sharing that.

**Comment by Keith94** [comment]
>Thank you for sharing that.

No problem. Glad you like them. I'm biased when it comes to orange so my hovers and pressed buttons use #FB8C00 too lol.

This morning I did a little testing but the first chapter marker completely vanished across all videos, both stock and modernz.

So I really don't know what changed or why it's acting that way, and you got a completely different result, too.. I'll have to investigate more.

**Comment by Keith94** [comment]
Not yet tbh but that is definitely something to try. 

Something else I noticed was Modernz's OSC was affected when playing back HDR content so everything was extremely bright. Although that must be related to mpv, Windows itself, or something else.

**Comment by Keith94** [comment]
Even tried it with no-config but it still doesn't show up on stock. Happens with all videos.

For now I can just edit modernz,lua with n = 2 to get my desired result, which is mostly working.

**Comment by Samillion** [comment]
If I may ask, where are you getting your mpv binary (build) from? Maybe it has a different configuration by default. I would like to try it out.

**Comment by Keith94** [comment]
https://nightly.link/mpv-player/mpv/workflows/build/master/mpv-x86_64-windows-msvc.zip

Pretty sure it happens with all 3rd party builds too since they seem identical.

**Comment by Keith94** [comment]
But it's not really related to modernz anymore, and if it's working as intended for you, that's all I needed to know. :p

**Comment by Keith94** [comment]
Yeah I absolutely will and thanks for all the support as always
