### ISSUE TITLE
Don't show window controls within window when set to "auto"

### ISSUE THREAD

**Issue by SimonSteinberger** [Samillion/ModernZ#206]
### mpv Information

Latest from 2024-11-11

### Reproduction Steps

In "mpv.conf" set `border=yes`
In "modernz.conf" set `windowcontrols=auto`
Open MPV in window mode.

### Expected Behavior

In auto mode, window controls should be shown whenever the system default controls are *not* shown.  When enabling borders, system default controls are shown in the native window, but not in fullscreen mode. Hence, for `windowcontrols=auto` the ModernZ MPV controls should only be shown in fullscreen, because in window mode there are already the default controls.

### Actual Behavior

In the native window, both controls are shown simultaneously: the system default controls AND the ModernZ MPV window controls.

Fix:
Replace
  `return not (state.border and state.title_bar) or state.fullscreen`
with
  `return not (state.border and state.title_bar) and not state.fullscreen`
in 
  `local function window_controls_enabled()`

Is this a bug or a feature? Anyways: Thanks for the wonderful script!!

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
Could you explain further, please? The intended use is to show controls in fullscreen state, when native window controls are not available. To help you close, minimize or restore the window condition.

Windowed mode:

![image](https://github.com/user-attachments/assets/844ac44f-966c-43de-9cfc-6bd10bd20840)

Full screen:

![image](https://github.com/user-attachments/assets/69670d56-69cc-4adb-a016-9e1c40fa2525)

The suggestion you provided removes window controls in fullscreen state. If that is what you want, you can simply add the following to your `mpv.conf`

```ini
[ModernZ-Fullscreen]
    profile-desc=No window controls in fullscreen
    profile-cond=fullscreen
    profile-restore=copy-equal
    script-opts-append=modernz-window_title=no
    script-opts-append=modernz-window_controls=no
```

**Comment by SimonSteinberger** [comment]
Oh man, I mixed up two things and was a bit confused :-P Yes, you're right, I originally didn't want the controls in fullscreen.

A conditional profile! Yes, that's a cool solution to get this done. Perfect, thanks 👍
Sorry for the silly issue report!

**Comment by Samillion** [comment]
>  Sorry for the silly issue report!

❤️ 

Not at all, please never hesitate to share your input even when you're not sure. It honestly helps in getting an overall feedback on specific features, and sometimes we discover unexpected bugs from it.
