### ISSUE TITLE
cache loading speed

### ISSUE THREAD

**Issue by thcehocai** [Samillion/ModernZ#213]
### Expected behavior of the wanted feature

May I ask if the cache loading speed can be displayed? For example, 1MB/s?

**Comment by Samillion** [comment]
Technically it's possible, but this needs to be requested at mpv.

Since `yt-dlp` already shows download speed, ie:
```
[download]   0.5% of  247.24MiB at 30.59MiB/s ETA 00:30
```

mpv would need to add a property to display such information. ie: `ytdl/current/speed` and `ytdl/current/eta`

If one exists though, let me know and I'll gladly implement it

**Comment by thcehocai** [comment]
Sorry, I'm not very familiar with everything about MPV, but the official documentation includes cache speed: Current I/O read speed between the cache and the lower layer (like network) This gives the number bytes per second over a 1 second window (using the type MPV_FORM-INT64 for the client API). I don't know how to call this parameter to display it.

**Comment by Samillion** [comment]
Oh, true! https://mpv.io/manual/master/#command-interface-cache-speed

I'll play around with it and come up with an implementation soon.

**Comment by thcehocai** [comment]
Thank you very much！

**Comment by thcehocai** [comment]
Also, how to set OSC not to display when the mouse is moved over the screen? I have removed all the controls above the screen and set bottomhover=yes, because the movement of the mouse at the top and middle should not trigger the display of OSC.

**Comment by Keith94** [comment]
>movement of the mouse at the top and in the middle should not trigger the display of OSC，But it will still trigger.

Definitely an oversight possibly carried over from previous forks. Would have to be fixed in the code or as part of #212 

On the topic of cache maybe could add cache duration as well and combine it together with cache speed? Like show duration as a tooltip of it or vice versa.

Don't know how Sam plans to add it, either with text element before the remaining/total timestamp or something else.

**Comment by Samillion** [comment]
> Don't know how Sam plans to add it, either with text element before the remaining/total timestamp or something else.

Exactly what I was thinking. My initial idea was to add the same cache element as stock osc (cached time), and next to it a cache speed element.

Displayed as:
```
[cached time] / [cache speed] • [remaining time]
```

Options:
```
cache_time = true,
cache_speed = true,
```

**Comment by Keith94** [comment]
I think it would work well, since the text should be pretty small and wouldn't take up a lot of room even in a theoretical "compact mode," or it could be adjusted as necessary for different layouts.

**Comment by thcehocai** [comment]
There is another issue. When I use external subtitles, some subtitles are too low or too high. I adjust the sub position for a more comfortable viewing experience. However, if I set raise_subtitles=yes, the sub position will return to the default 100% position after OSC is hidden, which forces me to adjust it again. Is there any way to solve it?

**Comment by Keith94** [comment]
It seems the function adjust_subtitles modifies `sub-pos` value and doesn't properly take into account if you use hotkeys like `r` and `R` to change the sub-pos.

https://github.com/Samillion/ModernZ/blob/3135a35194070defa80d21a00f27cd63b2952db5/modernz.lua#L1967-L1968

Looks like it's setting it back to 100 I believe.

Temporary workaround, you can add `sub-margin-y=<value>` in mpv.conf. This property should have no issues when using raise_subtitles

**Comment by Keith94** [comment]
There should probably be additional logic added to the function so that raise_subtitles doesn't do anything if subtitles are already positioned high enough (maybe a threshold of x amount of pixels or percentage) above the OSC.

**Comment by thcehocai** [comment]
Is it possible to keep subtitles at a fixed distance from the bottom when they are raised, without relying on sub_position? Alternatively, if you want to use sub_position, add a setting to use a user-defined parameter when raising subtitles. For example, if the user sets this parameter to sub_position=80%, it will be used when raising subtitles.

**Comment by Keith94** [comment]
It's a good idea; have to wait for the owner @Samillion to fix that at some point 😄

**Comment by Samillion** [comment]
> There is another issue. When I use external subtitles, some subtitles are too low or too high. I adjust the sub position for a more comfortable viewing experience. However, if I set raise_subtitles=yes, the sub position will return to the default 100% position after OSC is hidden, which forces me to adjust it again. Is there any way to solve it?

Could you open another bug issue about this, please? Otherwise I might forget due to workload.

**Comment by Samillion** [comment]
> Also, how to set OSC not to display when the mouse is moved to the top of the screen? I have removed all the controls at the top of the screen and set bottomhover=yes, so the movement of the mouse at the top and in the middle should not trigger the display of OSC，But it will still trigger.

I've applied a fix for it in https://github.com/Samillion/ModernZ/pull/220

In `modernz.conf` if you set
```EditorConfig
window_top_bar=no
```

or 
```EditorConfig
window_title=no
window_controls=no
```

It will not show osc if you hover in the top window area

**Comment by Samillion** [comment]
Any suggestions on where to place it and how it should be displayed:

Right now I have it in the same line as the title (far right)

![image](https://github.com/user-attachments/assets/0ea0a15b-fce9-45ef-8c7a-5e7d1ce6ec40)

Also, speed should be displayed for network streams (ie: URL/online) only or everything?

**Comment by thcehocai** [comment]
> Also, speed should be displayed for network streams (ie: URL/online) only or everything?
I think the position of the diagram is already quite good.
Personally, I believe that displaying cache speed for all files is better.

**Comment by Samillion** [comment]
> Is it better to bring a cache speed of/s?

It is updated per second.

> demuxer-cache-state:
> raw-input-rate is the estimated input rate of the network layer (or any other byte-oriented input layer) in bytes per second.

Maybe I should add `/s` to clarify it.

> I think the position of the diagram is already quite good.

Same. Though I'm hesitant a bit on some points:
- Should the `Cache:` label be displayed?
- Should the font size for cache info be even smaller than timestamp?
- Should the position change to be in the same line as timestamps? (ie: far right, before remaining time)

**Comment by Samillion** [comment]
@Xurdejl would love your input on this as well, if it's not a bother.

**Comment by thcehocai** [comment]
> * 是否应该显示 `Cache:` 标签？

It would be great if users could customize the display, as everyone's preferences are not the same.

**Comment by Samillion** [comment]
Agreed.

About position, it looks very strange when it's next to the timestamp. The only area that looks good is like what's shown in the previous screenshot I posted.

I'll wait a while to see if someone suggests a better placement position.

For font size, I'm thinking of making it smaller by 2 pixels.

I'll post a test script soon so you guys can see it in action.

**Comment by Samillion** [comment]
User options update:
```lua
cache_info = true,                     -- show cache information
cache_speed = true,                    -- show cache speed per second
cache_font_size = 16,                  -- font size of the cache information
cache_color = "#FFFFFF",               -- color of the cache information
```

Localization:
```lua
local language = {
    ["en"] = {
        cache = "Cache",
    },
}
```

![image](https://github.com/user-attachments/assets/e4138aa1-61be-4431-86e7-933d86a063c2)

**Comment by Samillion** [comment]
I think it looks good now with reasonable options to control it. Though I'm not sure about `@`.

**Comment by Samillion** [comment]
**Test script:** https://github.com/Samillion/ModernZ/commit/6729b835d77b73a9c0feaf01a3888e6429434340
https://github.com/Samillion/ModernZ/blob/dev_cach_info_feat/modernz.lua

I would love a suggestion for a better replacement for `@` within the cache info format.

```
Cache: [cached time] @ [speed per second]
```

Also, should `cache_info` be enabled by default?

**Comment by thcehocai** [comment]
> 测试脚本： 6729b83 https://github.com/Samillion/ModernZ/blob/dev_cach_info_feat/modernz.lua
> 
> 我希望得到一个关于在缓存信息格式中更好地替换 `@` 的建议。
> 
> ```
> Cache: [cached time] @ [speed per second]
> ```
> 
> 另外，默认情况下应该启用 `cache_info` 吗？

Perhaps we can simply separate them, for example:Cache: [cached time] Speed: [speed per second]?
By default, I don't think it's necessary to enable it because the cache color of the progress bar may be more noticeable when caching is enabled.

**Comment by Samillion** [comment]
> By default, I don't think it's necessary to enable ‘cache_info’ because the cache color of the progress bar may be more noticeable when caching is enabled.

Good point, I agree.

> Perhaps we can simply separate them, for example:Cache: [cached time] Speed: [speed per second]?

I'm worried that the `cache_info` line would be too long that way. Would replacing `@` with `•` look better?
```
Cache: [cached time] • [cache speed per second]
```

If you test the script, please let me know if anything is not working or needs adjusting.

Also, I apologize this took me a while to work on. I had to catch up on some things with my life.

**Comment by thcehocai** [comment]
![image](https://github.com/user-attachments/assets/989b78aa-edfc-4afd-8880-390a75e93c5b)




> * Should the position change to be in the same line as timestamps? (ie: far right, before remaining time)

Perhaps it is indeed necessary to put all cached information here, otherwise too long titles may obscure it.

**Comment by Samillion** [comment]
Nice catch. I'll fix it so the title does not overlap with the cache information.

**Comment by Samillion** [comment]
Would this position be better use of space? (under title)

![image](https://github.com/user-attachments/assets/3efe3be4-363b-433a-ae80-daf24f26e756)

**Comment by Samillion** [comment]
**Updated script:** https://github.com/Samillion/ModernZ/blob/dev_cach_info_feat/modernz.lua
**Commit:** https://github.com/Samillion/ModernZ/commit/af2cb4ed80b3a8bbffeb10dbd8e988dad6b69d1f

**Changes:**
- Replaced `@` with `•`
- Decreased `cache_info_font_size` to `12`
- Moved `cache_info` position under `title`

**Comment by Samillion** [comment]
Let me know if the updated script needs any adjusting, please.

**Comment by Samillion** [comment]
Updated.

**Script:** [dev_cache_info/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_cach_info_feat/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/8b355726367113566f87413a05f9af74cf45b14b

**Changes:**
- Improve `cache_info` position under the title
- Use mpv built in function to display speed per second `utils.format_bytes_humanized`
- Move `cache_info` related code under title related code
