### ISSUE TITLE
If title bar elements are disabled, top hover area and fade should be disabled as well

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#216]
### mpv Information

```bash
mpv v0.39.0-325-gd66ed2d8 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov 10 2024 00:40:04
libplacebo version: v7.349.0 (v7.349.0-19-g118d810-dirty)
FFmpeg version: N-117737-g10c02decc
FFmpeg library versions:
   libavcodec      61.24.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.46.100
   libswresample   5.4.100
   libswscale      8.9.101
```

### Reproduction Steps

In `modernz.conf` set:
```
windowcontrols=no
```

and/or
```
window_title=no
window_controls=no
```

### Expected Behavior

With all elements disabled, the title bar fade and hover area shouldn't be active

### Actual Behavior

The top area hover still shows osc and the top fade area still shows. https://github.com/Samillion/ModernZ/issues/213#issuecomment-2475790182

Also, consider renaming `windowcontrols` to something that relates to title bar. since that option disables all elements of title bar, not just the window controls.

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Keith94** [comment]
>Also, consider renaming windowcontrols to something that relates to title bar. since that option disables all elements of title bar, not just the window controls.

How about `show_title_bar` or simply `title_bar`?

**Comment by Samillion** [comment]
> How about `show_title_bar` or simply `title_bar`?

Good  suggestion, I'll use that.

**Comment by Keith94** [comment]
Or if you don't want to call it a bar could also call it show_top_area  or something like that

**Comment by Samillion** [comment]
> Or if you don't want to call it a bar could also call it show_top_area or something like that

Agreed, it should refer to the entire top area. Using "title" kind of assumes it's just a title.

At the moment I've set it to `window_top_bar`, which I think will be understood by all users at a glance.
