### ISSUE TITLE
sub_position when set raise_subtitles=yes

### ISSUE THREAD

**Issue by thcehocai** [Samillion/ModernZ#218]
### Reproduction Steps

When I use external subtitles, some subtitles are too low or too high. I adjust the sub position for a more comfortable viewing experience. If I set raise_subtitles=yes, the sub position will return to the  position I set after OSC is hidden.

### Expected Behavior

The subtitle position returns to the value I set.

### Actual Behavior

The sub position will return to the default 100% position after OSC is hidden.

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
Noted. Should be fixed soon.
