### ISSUE TITLE
`showtime` nil value

### ISSUE THREAD

**Issue by ctlaltdefeat** [Samillion/ModernZ#224]
### Reproduction Steps

.

### Expected Behavior

.

### Actual Behavior

The OSC doesn't load, and this shows up:

`modernz.lua:2736: attempt to perform arithmetic on field 'showtime' (a nil value)`

I'm using the latest version of `modernz.lua`

Interestingly, the error only occurs on one of my screens (`--screen=0`). Everything works when I use `--screen=1`, which is the usual screen I use. So the error is somehow screen dependent. Let me know what I should debug.

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
The state `showtime` is `mp.get_time()`

> Let me know what I should debug.

Please provide the requested information in the issue template.
- mpv version/information
- log file with the issue reproduced in it
  - Use: `mpv sample.mp4 --log-file=output.txt` [[details](https://mpv.io/manual/master/#options-log-file)]

**Comment by Samillion** [comment]
Also, please try to reproduce the issue with `--no-config` and let me know if it still occurs there as well.

**Comment by ctlaltdefeat** [comment]
It's rather odd, the error seems inconsistent...perhaps some timing condition? 
The error has a higher chance to occur the closer the configuration is to resembling my usual setup. I've reproduced two logs of the same configuration, one with the error occurring and one without. In the following, I've removed all other scripts besides modernz from my scripts dir.

`mpv --log-file=output.txt --screen=0 'C:\Users\Jonathan\Downloads\dolby-vision-amaze-(dolby-vision)-(www.demolandia.net).mp4'`

[output_no_error.txt](https://github.com/user-attachments/files/17786790/output_no_error.txt)
[output_error.txt](https://github.com/user-attachments/files/17786791/output_error.txt)

Looking at a file diff of the two, I don't see anything the catches my attention other than the fact that `[modernz] osc_init` appears 4 times in the one without error and only twice in the one with the error, but I'm not sure what that means.

**Comment by Samillion** [comment]
Are you able  to re-produce the error with `--no-config`?

**Comment by ctlaltdefeat** [comment]
No, and I don't seem to get the error with:

`mpv --no-config --script=C:\mpv\mpv\scripts\modernz.lua --osd-fonts-dir=C:\mpv\mpv\fonts --osc=no --screen=0 'C:\Users\Name\Downloads\dolby-vision-amaze-(dolby-vision)-(www.demolandia.net).mp4'`

either

**Comment by Samillion** [comment]
This suggests the problem is with your configuration. I'm going through your log file right now to try  and help you find the problem.

**Comment by ctlaltdefeat** [comment]
Thanks. I was incrementally commenting out sections of my configuration, until I realized that, like shown above, the same configuration can yield an error or not.

**Comment by Samillion** [comment]
I have a feeling it's your `force-window` config
https://mpv.io/manual/master/#options-force-window

> Warning
> 
> The window is created only after initialization (to make sure default window placement still works if the video size is different from the --force-window default window size). This can be a problem if initialization doesn't work perfectly, such as when opening URLs with bad network connection, or opening broken video files. The immediate mode can be used to create the window always on program start, but this may cause other issues.

**Comment by ctlaltdefeat** [comment]
You're right, that seems to fix it. Do you think it's worth trying to accomodate this option such that the OSC is able to eventually load? That is the behavior with the default OSC, at least.

**Comment by Samillion** [comment]
Window creation and initiation happens at runtime (ie: mpv side of things). 

I can try to think of a way to only initialize OSC on vo output (ie: window exists)

I predict this is going to be slow though, it's why stock `osc.lua` in itself doesn't use such methods. For this specific, it simply does a `~= nil` check on time invocation, which ModernZ uses the same, because we're based on stock osc.

**Comment by Samillion** [comment]
Fixed in https://github.com/Samillion/ModernZ/pull/474
