### ISSUE TITLE
the ability to hide the Audio 1/1 and the subtitiles buttons .

### ISSUE THREAD

**Issue by houssemko** [Samillion/ModernZ#225]
### Expected behavior of the wanted feature

An option to do so in the configuration file

**Comment by Samillion** [comment]
Should it hide the buttons automatically or should it be a user defined behavior?

As in `hide_subs_empty = yes/no/auto` or simply hide it without bothering the user?

**Comment by houssemko** [comment]
I think it should be hidden automatically

**Comment by Samillion** [comment]
I was just about to implement this, but quickly came into a scenario where hiding the audio and subtitle track buttons becomes a problem.

- A video with audio and/or subtitles available
- Manually disable either audio or subtitles
- Button disappears
- Re-enabling becomes a chore, since button is not there anymore

**Comment by Keith94** [comment]
I'm not OP but I kinda thought he meant disable the buttons if the track(s) don't exist in the file (and external tracks are not loaded either)?

But if a track exists and is toggled off, then show the button grayed out, to allow for easy re-enabling.

**Comment by houssemko** [comment]
Yeah that's what I meant

**Comment by Samillion** [comment]
> I'm not OP but I kinda thought he meant disable the buttons if the track(s) don't exist in the file (and external tracks are not loaded either)?

Ah, noted. The 1/1 in title implied an existing single track.

**Comment by houssemko** [comment]
about that , wouldn't pressing the volume button that's next to the slider mute and unmute the audio ? the same action to do with the audio button . So it's redundant to have both buttons

**Comment by Samillion** [comment]
> about that , wouldn't pressing the volume button that's next to the slider mute and unmute the audio ? the same action to do with the audio button . So it's redundant to have both buttons

They may seem similar, but they're different.

To use an old analogy: in an audio CD player:
- The volume/mute button controls speakers
- The audio button is the CD itself

Clicking the audio button removes or changes the tracks (ie removes the CD). It may result in silence, but the function is different.

**Comment by houssemko** [comment]
ow okay , I don't have use for it . I mainly use MPV to watch videos

**Comment by houssemko** [comment]
I understand , I guess it's not possible to let the user pick to enable it or disable ?

**Comment by Samillion** [comment]
Oh, no no. I'll make it auto hide if no tracks exist for audio/subtitle as you and Keith clarified.

**Comment by houssemko** [comment]
That's great

**Comment by Samillion** [comment]
Done. https://github.com/Samillion/ModernZ/issues/423
