### ISSUE TITLE
Consider disabling hover and held effects for non-interactable elements

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#227]
### Expected behavior of the wanted feature

1. Add following to modernz.conf
```
title_mbtn_left_command=ignore
title_mbtn_right_command=ignore
chapter_title_mbtn_left_command=ignore
chapter_title_mbtn_right_command=ignore
showtitle=yes
show_chapter_title=yes
```
2. Play a video file that includes chapters
3. Hover the title and chapter title elements

I think it would be better to have effects disabled on mouse hover and mouse press to indicate they're non-interactable

**Comment by Samillion** [comment]
Ah, you mean to add an ignore state for interactions in which the hover effects are disabled in?

**Comment by Keith94** [comment]
Ya if I understood correctly, essentially check if the left and right click events are set to ignore (for any of the customizable commands) and if so, don't apply hover or held effects to such buttons in that case 

Not exactly sure if you could use an approach like https://github.com/Zren/mpv-osc-tethys/commit/83df9d4

```lua
(element.eventresponder["mbtn_left_down"] == nil)
```

**Comment by Commander07** [comment]
Above PR should resolve this issue however leaving the value blank should work for disabling interaction too. So the below config should work fine even without my PR.
```
title_mbtn_left_command=
title_mbtn_right_command=
chapter_title_mbtn_left_command=
chapter_title_mbtn_right_command=
showtitle=yes
chapter_title_button=yes
```

**Comment by Keith94** [comment]
Perfect, thanks! I did not even know that. Will test soon.
