### ISSUE TITLE
Loop button

### ISSUE THREAD

**Issue by AndyNevergood** [Samillion/ModernZ#236]
### mpv Information

```bash
.
```

### Reproduction Steps

 I think these buttons are switched around.

### Expected Behavior

    loop_off = "\239\133\181",
    loop_on = "\239\133\178",

### Actual Behavior

    loop_off = "\239\133\178",
    loop_on = "\239\133\181",

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
They are in the intended order, which is click behavior, not "current state". As in, it shows you what happens if you click the button.

**Comment by AndyNevergood** [comment]
Understood.

**Comment by Keith94** [comment]
Fixed in current build https://github.com/Samillion/ModernZ/pull/498#issuecomment-4019809285
