### ISSUE TITLE
Adjust osc height if title commands disabled

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#241]
### Expected behavior of the wanted feature

@Samillion Thank you for the fix at #238. Can I request one small addition to that?

Can the fix also check if title interaction has been disabled via `title_mbtn_left_command=` and `title_mbtn_right_command=` or `ignored` states, and set OSC height to 110, as well?

That way, the unclickable title isn't extending the height and blocking any user inputs.

**Comment by Anthonyy232** [comment]
Would love this too :D

**Comment by Samillion** [comment]
This should be simple to implement with something like:
```lua
    local no_title_function = 
        not (user_opts.title_mbtn_left_command and user_opts.title_mbtn_left_command ~= "ignore") or
        not (user_opts.title_mbtn_right_command and user_opts.title_mbtn_right_command ~= "ignore")
```

I'll make a PR for it in a bit.

**Comment by Samillion** [comment]
**Test script:** [osc_height/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_title_function_osc_height/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/3a16684da252e9bd33fff67715ad5e48b7483aef

I'm hesitant about the use of `or`, it should be `and`. Right? I think.
```diff
    local no_title_function = 
        not (user_opts.title_mbtn_left_command and user_opts.title_mbtn_left_command ~= "ignore") 
-        or
+        and
        not (user_opts.title_mbtn_right_command and user_opts.title_mbtn_right_command ~= "ignore")
```

**Comment by Keith94** [comment]
Thanks for adding that. I actually don't know myself lol. Is there any issue with using or?

**Comment by Samillion** [comment]
With `or`:
- If one of them is disabled, osc height is decreased. (so left click can be functional, and still decreases height)

With `and`:
- if both of them are disabled, osc height decreases

**Comment by Keith94** [comment]
Yeah I would agree to use and. Otherwise if you only disable LMB command, and something is assigned to RMB, then RMB won't work properly, I assume.

**Comment by Samillion** [comment]
Updated script to use `and` instead of `or`. If it's not a bother, could you test and check if everything is working as intended? There is no rush, take all the time you need..

**Comment by Keith94** [comment]
I'm AFK but I will check later. I'm assuming the code is solid though.

**Comment by Keith94** [comment]
For me it's not working when the command values are blank. It works properly when commands are set to `ignore` though.

**Comment by Samillion** [comment]
Ah, oops. That was my bad, I was checking `true/false` and `ignore`, the `true/false` check should be `empty` check instead.

If I may ask, should it decrease height if value is empty? or specifically when it is set to `ignore`?

I only ask because in my head, using ignore only makes sense, it explicitly declares intent to ignore it, while an empty value is vague.

I wanted to know others' preference before I impose my own.

**Comment by Keith94** [comment]
>If I may ask, should it decrease height if value is empty? or specifically when it is set to ignore?

I always felt like it should decrease the height if it's either empty or ignored, since these both seem to result in the same behavior (or lack of).

**Comment by Samillion** [comment]
Updated.

**Script:** [osc_height/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_title_function_osc_height/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/8839ab548fa12b1e638631467ec8235647b2189f

Changes:
- Decrease OSC height if title function is set to `empty` or `ignore`.

**Comment by Keith94** [comment]
Sweet, it works really well now. Thanks for adding.
