### ISSUE TITLE
Changing colors in mpv.conf doesn't work properly

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#248]
### Reproduction Steps

1. Open mpv.conf
2. Add the following as an example

```
script-opts-append=modernz-side_buttons_color=#BE29B5
script-opts-append=modernz-middle_buttons_color=#BE29B5
```

### Expected Behavior

Aforementioned buttons are purple

### Actual Behavior

Aforementioned buttons are transparent.

[   0.013][w][modernz] '' is not a valid color
[   0.013][w][modernz] '' is not a valid color

### Log File

[log.txt](https://github.com/user-attachments/files/17882099/log.txt)

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
This is normal mpv behavior. It's stripping everything after `#` as a comment, hence why it doesn't see it. In cases like this, simply wrap the value in quotes.

**Example:**
```EditorConfig
script-opts-append="modernz-side_buttons_color=#BE29B5"
script-opts-append="modernz-middle_buttons_color=#BE29B5"
```

**Comment by Keith94** [comment]
Hmm, it needs to have # removed and be wrapped in quotation marks to render properly.

`#BE29B5` -> bugged
`'BE29B5'` -> read properly

Interesting...

**Comment by Keith94** [comment]
Oh ok, just saw your comment. Thanks, will do.

**Comment by Samillion** [comment]
> Hmm, it needs to have # removed and be wrapped in quotation marks to render properly.
> 
> `#BE29B5` -> bugged `'BE29B5'` -> read properly
> 
> Interesting...

It's the way mpv config is parsed.

In essence, if it starts with `color=#RRGGBB` it will read it as a color just fine.

However, if it's `option=sub-option=#RRGGBB` it reads `#RRGGBB` as a config comment line, so it's ignored.

**Comment by Keith94** [comment]
That's very good to know.. I thought it only counted "new" separate lines as comments. Learned something new.
