### ISSUE TITLE
Show OSC while mouse drag seeking when bottomhover=true

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#249]
### Reproduction Steps

1. Open a file
2. Click and hold the seekbar handle
3. Move mouse cursor above the OSC boundaries and continue to scrub through the video

### Expected Behavior

OSC stays visible while scrubbing like stock mpv behavior

### Actual Behavior

OSC hides according to `hidetimeout`

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
Ah, nice find. That's because of `mouse_seek_pause`. If it's set to `no`, it doesn't account for `state.playingWhilstSeeking`.

**Comment by Samillion** [comment]
Actually, disregard my comment, it's not the cause.

I'm unable to reproduce the behavior you're describing. I think it might be your `bottomhover_zone` configuration.

https://github.com/user-attachments/assets/c95d7491-1019-4946-bd21-5e6431864a6d

**Comment by Keith94** [comment]
The issue was happening if you move your cursor above the OSC, for example to the middle of the window, while continuing to seek with the mouse.

Initially I thought it happened all the time. However now I'm not so sure. I'll get back to you on it.

**Comment by Keith94** [comment]
Here is a capture of the issue vs stock behavior.

Note: It does only occur when bottomhover is true. When set to "no" it behaves just like stock.

https://github.com/user-attachments/assets/4ece3941-df39-4d0a-853a-cade8399a871

**Comment by Keith94** [comment]
That's all good then.

**Comment by Samillion** [comment]
To elaborate further, bottom hover is handled within the mouse move event:
https://github.com/Samillion/ModernZ/blob/06cc6515f0ff000a988cb5a735d914b0aec91991/modernz.lua#L2836

Pressing down event is handled here, while it does reset timeout, it does not force osc to show:
https://github.com/Samillion/ModernZ/blob/06cc6515f0ff000a988cb5a735d914b0aec91991/modernz.lua#L2798-L2816

Same as `osc.lua`:
https://github.com/mpv-player/mpv/blob/4ff9f50b6b76bb6ccd008710d8d7a76b4750d249/player/lua/osc.lua#L2176

The difference between the two is `deadzone` vs `bottomhover` behavior. They're both similar in function, but different in the process itself.

If this feature is desirable by users in the future, we can add a handler on mouse press to force osc to show as long as an element is pressed/held down.
