### ISSUE TITLE
Some OSC buttons overlap if window cannot fit them all

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#25]
Demonstrated in the video posted in https://github.com/Samillion/ModernZ/issues/24#issuecomment-2416585074

**Comment by Keith94** [comment]
Oddly enough, I can still reproduce with the latest update i.e. the osc still pops up over subs like in the video :(

**Comment by Samillion** [comment]
This fix addresses the following: (in your video it shows the volumebar overlapping due to scale)

https://github.com/user-attachments/assets/fd3bb1c6-fd7e-4974-ad3b-347c76fd9ea7

> Oddly enough, I can still reproduce with the latest update i.e. the osc still pops up over subs like in the video :(

It doesn't fix itself? I'll see what I can do to improve.

**Comment by Keith94** [comment]
Oh wow, I did not even notice the volume issue was a thing. Thanks for clarifying 

>It doesn't fix itself? I'll see what I can do to improve.

Yeah it technically does once the osc times out. By default its set to 2 seconds I think. Thanks again
