### ISSUE TITLE
Unable to read title

### ISSUE THREAD

**Issue by thcehocai** [Samillion/ModernZ#252]
### Reproduction Steps

Play video files

### Expected Behavior

Display the title correctly

### Actual Behavior

Title displayed as mpv 
The chapter is displayed as nil
The console displays' Command 'escape pass' not found'

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
That's because you're using an outdated mpv, similar to https://github.com/Samillion/ModernZ/issues/131 and https://github.com/Samillion/ModernZ/issues/120

**Comment by thcehocai** [comment]
Thank you, I was inspired. The branch version I used actually returned to normal after replacing the second to last libmpv-2.dll.

**Comment by Samillion** [comment]
Awesome. I'm glad it all worked out.
