### ISSUE TITLE
Disable showing OSC when moving mouse to the top

### ISSUE THREAD

**Issue by da3dsoul1** [Samillion/ModernZ#257]
### Expected behavior of the wanted feature

I really enjoy this OSC, but i'm a bit frustrated by the fact that it makes itself visible when I hover mouse over the top. Please could you add an option to disable that? I only want osc to show itself when hovering at the bottom.

Here's a video showing what I would like to disable:
https://github.com/user-attachments/assets/6dcd6469-e741-4417-81a8-ebaeac6ab2df
As you can see it also adds a shadow effect, which is also needs to be disabled.

P.S.: Osc functions exactly as I want it to while windowed, this issue only appears in fullscreen.

**Comment by Keith94** [comment]
Update modernz in order to fix the bug you're describing: https://github.com/Samillion/ModernZ/releases/tag/v0.2.2

As far as not showing the bottom geometry when hovering at the top, it's been discussed but currently stalled: https://github.com/Samillion/ModernZ/discussions/212

**Comment by Samillion** [comment]
Indeed, this was fixed by https://github.com/Samillion/ModernZ/pull/220

> As far as not showing the bottom geometry when hovering at the top, it's been discussed but currently stalled: https://github.com/Samillion/ModernZ/discussions/212

Thank you very much for reminding me on that. Though I won't lie, I need to think on how to implement area specific hover.

**Comment by Keith94** [comment]
That's no problem. It's fairly low priority for me and hasn't been requested a lot.

**Comment by da3dsoul1** [comment]
Thank you so much!!!!! It's now the OSC of my dreams!
