### ISSUE TITLE
Modify the font (size/color/shadow...) of the interactive menu

### ISSUE THREAD

**Issue by jiangzhenjerry** [Samillion/ModernZ#259]
### Expected behavior of the wanted feature

Is there a way to modify the font size/color/shadow of the interactive menu? I glanced through the code and it seems like it's not controlled by ModernZ. Rather, it seems to be controlled by mpv itself. I admit I'm a little lost about where exactly it is. Can anyone enlighten me on this? Thanks!

<img width="374" alt="1" src="https://github.com/user-attachments/assets/d9c18372-9a69-4301-a9ef-4e8174de1a5e" />

**Comment by Keith94** [comment]
I believe you can create script-opts/console.conf and add any of the following configuration to it. I don't think it supports color changes.

https://mpv.io/manual/master/#console-font

**Comment by Samillion** [comment]
Indeed. This is in the mpv side of things.. Additional to what Keith said, I think it also supports osd font options.

CC @guidocella

**Comment by jiangzhenjerry** [comment]
Makes a lot of sense. Thank you both for the guidance! Closing this now...

**Comment by guidocella** [comment]
Fixed by https://github.com/mpv-player/mpv/pull/15528

**Comment by jiangzhenjerry** [comment]
@guidocella Thank you! Is there a plan to inherit things like `--osd-outline-size`, `--osd-shadow-offset`... too?

**Comment by guidocella** [comment]
console has its own `border_size` script-opt to change the outline size. The default value is different than `--osd-outline-size` so it is not inherited. Though personally I make all fonts and sizes the same with

```lua
mp.observe_property('osd-font', 'string', function (_, font)
    mp.commandv('change-list', 'script-opts', 'append', 'console-font=' .. font)
end)
mp.observe_property('osd-font-size', 'string', function (_, size)
    mp.commandv('change-list', 'script-opts', 'append', 'console-font_size=' .. size)
    mp.commandv('change-list', 'script-opts', 'append', 'stats-font_size=' .. size)
end)
mp.observe_property('osd-outline-size', 'string', function (_, size)
    mp.commandv('change-list', 'script-opts', 'append', 'console-border_size=' .. size)
    mp.commandv('change-list', 'script-opts', 'append', 'stats-border_size=' .. size)
end)
```

(in select mode, console already inherits `--osd-font`, and https://github.com/mpv-player/mpv/pull/15527 is needed to change stats script-opts)

I am not sure if `--osd-shadow-offset` should be inherited in `outline-and-shadow` border style, because currently console has different x and y shadow sizes and `--osd-shadow-offset` doesn't allow that; I even wrote it in https://github.com/mpv-player/mpv/commit/2e31502cb1

I was also never sure about the `default_item` color, maybe it should also use `--osd-selected-color` but without the bold? And should console autocompletions also use `--osd-selected-color`?

**Comment by Samillion** [comment]
> I was also never sure about the `default_item` color, maybe it should also use `--osd-selected-color` but without the bold?

Great idea, makes it easier at a glance to know which is which. Though I honestly think it's fine as is, the indicator `default` is more than enough and follows the typical standard of a selected item.

The only paradox is what we discussed on irc, more options make people happy, but also means even more people won't know about it.

**Comment by guidocella** [comment]
I don't understand what indicator you are talking about. Currently `default_item` is yellow like the default `--osd-selected-color` but not bold, but if you change `--osd-selected-color`, only the color of the selected item changes while `default_item` stays yellow. So maybe they should both follow `--osd-selected-color`.

**Comment by jiangzhenjerry** [comment]
@guidocella thanks for the detailed explanation. I learned a lot.

> I was also never sure about the `default_item` color, maybe it should also use `--osd-selected-color` but without the bold?

IMHO that'll be a good idea, unless there is a way to surface the setting for the `default_item` color.

> currently console has different x and y shadow sizes and `--osd-shadow-offset` doesn't allow that.

Makes sense. In this case, is it possible to set the console x/y shadow sizes? Such that I can mimic the `--osd-shadow-offset` behavior. I guess I'm suffering from mild OCD.

**Comment by Samillion** [comment]
> I don't understand what indicator you are talking about

Maybe I misunderstood. This is what I meant that it clearly shows default/selected.

![image](https://github.com/user-attachments/assets/0538a568-5ad2-42c7-987c-afe337abca97)

![image](https://github.com/user-attachments/assets/1b174942-1f8a-42d6-b641-ef96dfb6ddd5)

**Comment by jiangzhenjerry** [comment]
@guidocella Sorry for pinging you, but I noticed that if `scale_with_window=no` then the `border_size` option is not in effect. The border size remains the same whatever the value is. Will you kindly look into this?
