### ISSUE TITLE
Chapter title hover zone abnormal size

### ISSUE THREAD

**Issue by da3dsoul1** [Samillion/ModernZ#264]
### Reproduction Steps

Hover in the area below seek bar.

### Expected Behavior

Limit chapter title hover zone to actual chapter title, and not that huge empty space.

### Actual Behavior

Chapter title hover zone goes beyond boundaries. Here's a quick video demonstration:

https://github.com/user-attachments/assets/52fb8835-5472-449c-ae39-326853cf2118

P.S.: Sorry if it's supposed to be like that, I just find it to be rather peculiar behavior.

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
It is indeed the intended behavior, similar to title.

I get what you mean though. A large empty hover area when the content is barely 100 pixels wide. The original intent was "this is all reserved for chapter title".

Maybe it should calculate pixel width based on character count of `chapter_title`. I'll tinker with this and come back to ya.

**Comment by da3dsoul1** [comment]
Makes sense! Btw, thank you for fixing thumbnail preview black border that was displaying behind title name. I just downloaded lua from the repo itself and noticed the bug gone. Keep up the great work!

**Comment by Samillion** [comment]
Follow up here, please. https://github.com/Samillion/ModernZ/issues/208#issuecomment-2562212179
