### ISSUE TITLE
osc conflict with interactive menus

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#265]
### Reproduction Steps

1. Open a file with chapters
2. Click the chapter title button
3. Move your mouse quickly after you click

### Expected Behavior

osc hides properly while interactive menu is open

### Actual Behavior

osc is displayed on top completely broken

https://github.com/user-attachments/assets/1e3c412a-374c-4898-a240-18d9ffddfacd

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Keith94** [comment]
Oddly enough I can still reproduce, but I didn't troubleshoot yet.

**Comment by Samillion** [comment]
This fix draws the overlay/osc behind console/select. So even if both are up, osc will timeout and you can scroll/hover menu normally.

**Comment by Samillion** [comment]
Reference: https://github.com/mpv-player/mpv/pull/15189

**Comment by Keith94** [comment]
Isn't that issue only about the box layout? I'm not sure that it makes any difference for us. Could be wrong.

**Comment by Samillion** [comment]
ModernZ overlay is a box layout. (ie: a rectangle with a full width of window).

If you look at your video, you'll see the select menu is behind the OSC, with this update, the select menu is in front of the OSC which gives the menu a higher priority, letting osc hide/timeout and disappear. Even if visibility mode is always, select menu is still drawn above the OSC.

**Comment by Keith94** [comment]
Ohh okay. That should work fine. Thanks for the explanation.
