### ISSUE TITLE
Mute button tooltip shows too many decimals after volume change with trackpad

### ISSUE THREAD

**Issue by xiaoleichen** [Samillion/ModernZ#278]
### mpv Information

```bash
mpv 45c1c58 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov 18 2024 18:32:19
libplacebo version: v7.349.0
FFmpeg version: 7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Reproduction Steps

Adjust volume with trackpad or any other wheels that support precise seeking.
Hover mouse over volume control button

### Expected Behavior

No decimal digits

### Actual Behavior

A very long number.
<img width="337" alt="Screenshot 2024-12-28 at 4 29 12 PM" src="https://github.com/user-attachments/assets/7a36e0a7-41e7-4974-9c41-395868147942" />

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by Samillion** [comment]
This only occurs on volume icon and not the volume bar?
