### ISSUE TITLE
Add option to make specified buttons always enabled

### ISSUE THREAD

**Issue by BODZy** [Samillion/ModernZ#284]
Context:
When using custom commands for playlist_prev/next, the buttons remain inactive if the playlist is empty. I use a script to autoplay files from a folder without adding them to a playlist (Useful for example to switch between episodes without creating a playlist, etc).

**Comment by BODZy** [comment]
So far I'm using `ne.enabled = true` for these buttons, but a customization via config would be nice

**Comment by Samillion** [comment]
Interesting idea and we already have the means to do it.

Leaving notes to myself here so I don't forget, I'm not home at the moment. I'll tinker with it soon.

Add:  `user_opts.buttons_always_active`

Example usage in `modernz.conf`
```EditorConfig
buttons_always_active=playlist_prev,playlist_prev
```

Then in `ne.enabled`, we can use `contains()` function, example:
```lua
ne = new_element("playlist_prev", "button")
ne.enabled = contains(user_opts.buttons_always_active, "playlist_prev")
```

https://github.com/Samillion/ModernZ/blob/3a40bedd52cc733ff8a35d0e04a03237732d9bea/modernz.lua#L370-L386

**Comment by Samillion** [comment]
Are there any other buttons that could benefit from such option? Just to make a list of them.

**Comment by Samillion** [comment]
Off-topic: If I may ask, how come you're not letting mpv create a playlist for you?

```EditorConfig
#mpv.conf
prefetch-playlist=yes
directory-mode=ignore
autocreate-playlist=filter
directory-filter-types=video,image

image-exts=apng,avif,bmp,heic,j2k,jp2,jpeg,jpg,jxl,png,qoi,svg,tga,tif,tiff,webp
video-exts=3g2,3gp,asf,avi,f4v,flv,h264,h265,gif,m2ts,m4v,mj2,mkv,mov,mp4,mp4v,mpeg,mpg,ogv,rmvb,ts,webm,wmv,y4m
```

**Comment by BODZy** [comment]
> Off-topic: If I may ask, how come you're not letting mpv create a playlist for you?
For better compatibility with Syncplay. Also I don't need all files to be automatically added to the playlist, if necessary I create a playlist through the UOSC interface
![image](https://github.com/user-attachments/assets/06405445-4c11-4385-83d4-b70caa635a20)

**Comment by Samillion** [comment]
Done.
