### ISSUE TITLE
Display chapter name above time stamp

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#285]
### Expected behavior of the wanted feature

* When using thumbfast, show chapter name above time stamp (tooltip) but below thumbnail (rather than above).
* When not using thumbfast, show chapter name above time stamp too (rather than on same line)

**Comment by Samillion** [comment]
**Test script:** [chapter_tooltip/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_chapter_tooltip_refactor/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/3ff2603e8dc9501be4353ccef3b9ec89456fe30f

**Changes:**
- If `show_title` is disabled and `thumbfast` is not used, show hovered chapter title above the time code tooltip instead of appending it in the same time code line
- Align a min and max value so that on hover on end/start, chapter title tooltip doesn't go out of bound

![image](https://github.com/user-attachments/assets/f0023510-eb6c-4985-a89b-be918891a11c)

**Comment by Samillion** [comment]
**Updated:** [chapter_tooltip/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_chapter_tooltip_refactor/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/02d8e2b338d03052bec3d9dec8b013a37bb8b2a7

**Changes:**
- if `show_title` and `thumbfast` are disabled, but `show_chapter_title` is enabled, replace `chapter_title` with hovered chapter. Similar to how `title` is changed on chapter hover, if `show_title` is enabled and `thumbfast` is disabled.

![image](https://github.com/user-attachments/assets/54a1932c-b6f6-4c05-9fe8-f4943d2c7995)

**Comment by Keith94** [comment]
Thank you sir 🙏🏻 

If I'm using thumbfast, can the chapter also appear like https://github.com/Samillion/ModernZ/issues/285#issuecomment-2565150966 ?

**Comment by Samillion** [comment]
> If I'm using thumbfast, can the chapter also appear like [#285 (comment)](https://github.com/Samillion/ModernZ/issues/285#issuecomment-2565150966) ?

My only concern is how users are used to how it is now, since it's the "official" method even with thumbfast's own osc patch.

Do you mind if we delay this for a while? Just to ease users from all the sudden changes recently lol.

**Comment by Keith94** [comment]
Of course! Don't mind at all.

**Comment by Samillion** [comment]
Thank you very much for understanding and keeping an open mind. ❤️

**Comment by Keith94** [comment]
>When using thumbfast, show chapter name above time stamp (tooltip) but below thumbnail (rather than above).

For anyone who might be interested, I made a quick hack for this.

```diff
- local thumbMarginY = user_opts.time_font_size + thumbPad + 2 / r_h
+ local thumbMarginY = user_opts.time_font_size + thumbPad + 18 / r_h
```

```diff
- elem_ass:pos((thumbX + thumbfast.width / 2) * r_w, thumbY * r_h - user_opts.time_font_size / 2)
+ elem_ass:pos((thumbX + thumbfast.width / 2) * r_w, thumbY - 7 - user_opts.time_font_size / 2)
```

![mpv_vMkMYG8tmr](https://github.com/user-attachments/assets/1973e414-3144-4857-9dfa-4f1723b5a4ea)
