### ISSUE TITLE
Add user_opt to show/hide the buttons for next/previous track

### ISSUE THREAD

**Issue by Anthonyy232** [Samillion/ModernZ#34]
Hi, I can't seem to hide these buttons
![image](https://github.com/user-attachments/assets/5ddf2ecd-37a3-487c-8794-6c67909c63a8)

If I'm understanding correctly, it should be corresponding to one of these. I have both set to 'no'.
showjump=no
showskip=no

Config: https://pastebin.com/NVsGMprx

**Comment by Samillion** [comment]
Ah, you are right. Easy fix. Thank you for reporting, should be done today.

**Comment by Samillion** [comment]
Wait, just realized what you're showing is not the skip chapter buttons. That's the next/previous track buttons.

Will add a new user_opts for them.

**Comment by Samillion** [comment]
As requested, it has been implemented in [v0.1.4](https://github.com/Samillion/ModernZ/releases/tag/v0.1.4)
