### ISSUE TITLE
fr/hide fullscreen-window button

### ISSUE THREAD

**Issue by Anthonyy232** [Samillion/ModernZ#35]
Hi, can there be an option to hide this button?
![image](https://github.com/user-attachments/assets/26d010a4-e5cf-47eb-8a31-5c74fcc38d33)

Config:
https://pastebin.com/NVsGMprx

**Comment by Samillion** [comment]
The fullscreen toggle button? Hmmm, sure lol, I'll turn it into a user_opts in the next update.

**Comment by Samillion** [comment]
As requested, it has been implemented in [v0.1.4](https://github.com/Samillion/ModernZ/releases/tag/v0.1.4)
