### ISSUE TITLE
Tooltip text is gray

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#4]
Sometimes the tooltip text doesn't show as white like it normally does. Still didn't figure out the cause yet.

![image](https://github.com/user-attachments/assets/34c9be76-0e90-4b70-8e80-86aa8d8cfbe7)

**Comment by Samillion** [comment]
Oh, looks like it goes back in layer.

Hmm, maybe this is connecting to the other issue. Animation and element layering.

**Comment by Samillion** [comment]
Do you happen to remember what lead to this happening? For example, the sequence of actions you took that triggered this?

I'm also unable to replicate this as well, but I'm planning a do a full code check to debug everything I can.

**Comment by Keith94** [comment]
Seems to happen at random but more commonly if you have thumbfast also installed.

Funny thing is that thumbfast's thumbnail also sometimes renders behind the title (and just a white box for some reason).

![mpv_iDcidNtG81](https://github.com/user-attachments/assets/e836e8db-67e0-4385-9716-691d25ae080e)

**Comment by Samillion** [comment]
Thank you, so it looks like a layering issue, still can't replicate but at least it narrows it down.

https://github.com/user-attachments/assets/df80b6aa-0b56-4107-9e84-7e13f0a4de37

**Comment by Samillion** [comment]
@Keith94 Could you set this in modernz.conf please
```
livemarkers=no
```

**Comment by Keith94** [comment]
Behaves the same for me.
