### ISSUE TITLE
Make volume bar follow seekbar*_color

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#42]
Ref: https://github.com/dexeonify/mpv-config/commit/56a0a8523218e60baadd8bebea039ca34db8b20a

Maybe could have it togglable such as volume_follows_seekbar=<yes|no> or fully customizable.

**Comment by Samillion** [comment]
Hmmm. The user option `side_buttons_color` changes the volume bar color as well.

To do this, I'll have to add a user option to handle this, for example:
```ini
# Match volumebar color with seekbar color? It will ignore side_buttons_color for volume bar
volbarmatchseek=yes/no
```

Would that be a good solution?

**Comment by Keith94** [comment]
Yup, that would probably work just fine!
