### ISSUE TITLE
bug/can't get osc to show up when full screened

### ISSUE THREAD

**Issue by Anthonyy232** [Samillion/ModernZ#49]
Hi, not sure if it's just user error, but I can't get the osc to show up when the player is full screened. Updated MPV, using the latest versions of ModernZ.

My config:
https://pastebin.com/b8026RdN

**Comment by Xurdejl** [comment]
Hi, seems like a recent change named the option to show the fullscreen button the same as the option to show the osc on fullscreen.
I sent a pr with the fix

**Comment by Samillion** [comment]
Oops. That was definitely my bad. 😝
