### ISSUE TITLE
modernz.conf playlist comment

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#54]
https://github.com/Samillion/ModernZ/blob/main/modernz.conf#L40

>LClick: show playlist, RClick: use select.lua

Small bit of text that could use update/removal, since those functions got swapped by default now.

**Comment by Samillion** [comment]
Nice catch. Thank you very much.

You honestly deserve a contributor's credit. If you want, you can fork this repo, edit your fork's `modernz.conf` to correct that line by removing `LClick: show playlist, RClick: use select.lua`.

Then you can create a pull request here (Samillion/ModernZ <= Keith94/ModernZ)

I'll review, merge and you'll get the contributor's credit. You can delete the fork after the merge if you want.

Unless this is too much of a hassle of course, then I can do it myself. I merely mention this so you get the credit you deserve.

**Comment by Keith94** [comment]
Okay I'll give it a try in a bit. Shouldn't be too bad.
