### ISSUE TITLE
Support mpv title-bar option

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#72]
Set `title-bar=no` in `mpv.conf`. OSC title bar doesn't show up when hovering title bar area.

See https://github.com/mpv-player/mpv/pull/12894

**Comment by Samillion** [comment]
Huh, I thought I already added that.

https://github.com/Samillion/ModernZ/blob/54d04a0f920c885df92415e4043d7537711b6c52/modernz.lua#L2656-L2659

**Comment by Keith94** [comment]
Also `boxalpha` not supported with title bar disabled,

![mpv_OTBqRd8EXo](https://github.com/user-attachments/assets/790ddab3-fe81-492e-a530-fb12a577931e)

**Comment by Samillion** [comment]
Should be fixed.
- Respects title-bar config
- Show/hide top bar correct

**Comment by Keith94** [comment]
Works great !! Thanks for your efforts!
