### ISSUE TITLE
Keep osc visible while hovered during playback

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#75]
During playback the osc always hides according to `hidetimeout=` even if hovered by cursor. In edge case scenario, if someone set `hidetimeout=0` the osc is almost unusable while playing.

Paused playback is not affected (i.e. the osc stays while hovered). If you observe stock OSC and youtube, their osc also stays visible while playing and hovered.

Request: change default behavior or add option to toggle behavior to keep osc visible while elements are hovered

**Comment by Keith94** [comment]
It's fixed on line 2481 by changing
```lua
if not (state.paused and user_opts.keeponpause) then
```
to

```lua
if not user_opts.keeponpause then
```

**Comment by Xurdejl** [comment]
Making the behavior like that makes more sense. It always bothered me that the OSC kept hiding when I was using bottomhover, which is why I normally don’t use it

**Comment by Keith94** [comment]
Good to hear that. If Sam agrees too then I can go ahead and make PR with that change

**Comment by Samillion** [comment]
> Good to hear that. If Sam agrees too then I can go ahead and make PR with that change

Of course! Thank you very much for the catch and awaiting your PR. 😻

**Comment by Samillion** [comment]
@Keith94 Hai hai. I see you've applied the commit on your fork, just tagging you in case you forgot to PR in here so I can merge.

**Comment by Keith94** [comment]
Hi sorry I'm just running errands rn. Will do it very soon

**Comment by Samillion** [comment]
No rush at all, take all the time you need.

**Comment by Keith94** [comment]
Submitted here https://github.com/Samillion/ModernZ/pull/76 also feel free to change anything
