### ISSUE TITLE
Consider: Improve the look of Window Controls and Title (borderless)

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#8]
https://github.com/zydezu/ModernX/issues/49 Raised a good point.

Consider: 
- Increasing the font size of the title (18 -> 30)
- Increasing size of window controls (20 -> 25)
- Increase height and padding (30 -> 50)
- Adjust controls position [30, 74, 118] -> [25, 69, 113]
- Geo correction by 15, instead of 10.
- Max chars by 17, instead of 10.
- Add gold hover color to minimize and maximize buttons (similar to X's red)
- Increase rendered alpha height? (unsure)

![image](https://github.com/user-attachments/assets/6813f625-f049-429e-b250-42df45861bf9)

![image](https://github.com/user-attachments/assets/f667bcc7-bbeb-4ce3-9303-497e6c446829)

```lua
        WindowTitle = "{\\blur1\\bord0.5\\1c&HFFFFFF&\\3c&H0\\fs".. 30 .."\\q2\\fn" .. user_opts.font .. "}",
        WinCtrl = "{\\blur1\\bord0.5\\1c&HFFFFFF&\\3c&H0\\fs".. 25 .."\\fnmpv-osd-symbols}",
```

```lua
    local wc_geo = {
        x = 0,
        y = 50,
        an = 1,
        w = osc_param.playresx,
        h = 50,
    }
```

```lua
    local first_geo =
        {x = controlbox_left + 25, y = button_y, an = 5, w = 40, h = wc_geo.h}
    local second_geo =
        {x = controlbox_left + 69, y = button_y, an = 5, w = 40, h = wc_geo.h}
    local third_geo =
        {x = controlbox_left + 113, y = button_y, an = 5, w = 40, h = wc_geo.h}
```

```lua
        lo = add_layout("windowtitle")
        geo = {x = 15, y = button_y + 15, an = 1, w = osc_param.playresx - 50, h = wc_geo.h}
        lo.geometry = geo
        lo.style = osc_styles.WindowTitle
        lo.button.maxchars = geo.w / 17
```

```lua
lo.button.hoverstyle = "{\\c&H00D7FF&}" -- gold
```

**Comment by Keith94** [comment]
Can there also be an option to show the title and window controls separately?

**Comment by Samillion** [comment]
Oh, you mean an option to show/hide window title and another to show/hide the window controls? Yeah, that would be easy to implement.

I'm falling asleep right now xD but by tomorrow all of this should be done.

**Comment by Keith94** [comment]
Yes, exactly! No worries :)

**Comment by Samillion** [comment]
Reminder: Add `user_opts` colors for:
- Window title
- Window controls, one for each: close, max, min
