### ISSUE TITLE
[Feature Request] yt-dlp button

### ISSUE THREAD

**Issue by novaexe** [Samillion/ModernZ#84]
almost perfect, amazing work, this is all i can find that i think is missing.

**Comment by Samillion** [comment]
I was going to add this when I was re-doing the project at the start, but I stopped because I don't have access to Mac or Linux desktops. I have a couple of Raspberry Pis and NAS enclosures that run headless, nothing with a desktop environment though.

For example, on ModernX, they use:
```lua
local function openFolder()
    local device = "linux"
    if os.getenv("windir") ~= nil then
        device = "windows"
    elseif os.execute '[ -d "/Applications" ]' == 0 and os.execute '[ -d "/Library" ]' == 0 or os.execute '[ -d "/Applications" ]' == true and os.execute '[ -d "/Library" ]' == true then
        device = "mac"
    end

    -- for ubuntu
    local url_browser_linux_cmd = "xdg-open \"$url\""
    local file_browser_linux_cmd = "dbus-send --print-reply --dest=org.freedesktop.FileManager1 /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:\"file:$path\" string:\"\""
    local url_browser_macos_cmd = "open \"$url\""
    local file_browser_macos_cmd = "open -a Finder -R \"$path\""

    local cmd = ""
    if device == "linux" then
        cmd = file_browser_linux_cmd
    elseif device == 'windows' then
        localpath = localpath:gsub("/", "\\")
        local ret = mp.command_native_async({
            name = "subprocess",
            args = {"explorer", localpath}
        })
    elseif device == "mac" then
        cmd = file_browser_macos_cmd
    end 
    cmd = cmd:gsub("$path", localpath)
    if device ~= 'windows' then
        os.execute(cmd)
    end
end
```

I would change it to:
```lua
local function open_folder(localpath)
    local device = package.config:sub(1,1) == "\\" and "windows" or (os.getenv("OSTYPE") == "darwin" and "mac" or "linux")

    local commands = {
        linux = 'dbus-send --print-reply --dest=org.freedesktop.FileManager1 /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:"file://%s" string:""',
        mac = 'open -R "%s"',
        windows = {"explorer", "%s"} -- handled as subprocess
    }

    -- platform-specific 
    if device == "windows" then
        localpath = localpath:gsub("/", "\\") -- convert path separators for Windows
        mp.command_native_async({
            name = "subprocess",
            args = {commands.windows[1], string.format(commands.windows[2], localpath)}
        })
    else
        os.execute(string.format(commands[device], localpath))
    end
end
```

But unfortunately I can't test if my simpler logic works or not for the other platforms.

I'll tinker around and see if I can come up with a solid implementation. Give me a couple of days. I can't promise anything though, but I will do my best.

**Comment by novaexe** [comment]
awesome tyvm :D

**Comment by Samillion** [comment]
I've added the yt-dlp download feature here:
https://github.com/Samillion/ModernZ/blob/dev_ytdlp_download_241024/modernz.lua

Could you test and give feedback if you face any problems, please?

I'll bother @Keith94 and @Xurdejl in case they're interested as well.

**New options:**
```
# show download button on web videos (requires yt-dlp)
downloadbutton=yes

# the download path for videos
downloadpath=~~desktop/mpv

# optional parameteres for yt-dlp
# example "-f bestvideo[vcodec^=avc][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
ytdlpQuality=
```

**Comment by Samillion** [comment]
Ooops, there was a missing `,` I've updated the script, same link.

**Comment by novaexe** [comment]
awesomeness, works correctly so far in mpv.net, still has that weird yt-dlp container bug with some files where you have to rename it to .mp4 manually, but otherwise great 👍

**Comment by novaexe** [comment]
doesnt have the description like modernx but ey im just glad it works XD

**Comment by Samillion** [comment]
> awesomeness, works correctly so far in mpv.net, still has that weird yt-dlp container bug with some files where you have to rename it to .mp4 manually, but otherwise great 👍

Update yt-dlp and ffmpeg if you can, it will be fixed.

> doesnt have the description like modernx but ey im just glad it works XD

Youtube description/comments/likes is something I don't plan on adding, to be honest.
