### ISSUE TITLE
Touchpad triggers multiple inputs

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#85]
The bug was reported here https://github.com/zydezu/ModernX/issues/52 (closed) but still persists in modernx/modernz.

- Only the skip and jump buttons seem to exhibit the issue (`showskip=yes` or `showjump=yes`).
- Only happens when using a laptop touchpad and tapping the touchpad.
- The tactile physical clicks don't cause the issue.
- The default OSC doesn't cause the issue either.

the log captures it but doesn't capture my inputs

[log.txt](https://github.com/user-attachments/files/17484698/log.txt)

[2.308][v][cplayer] Set property: chapter -> 1
[...]
[2.483][v][cplayer] Set property: chapter -> 1

**Comment by Samillion** [comment]
So it triggers two actions per tap, right?

I'll investigate this and get back to you.

**Comment by Keith94** [comment]
Yes, exactly that. mpv handles it flawlessly so maybe they have something in their codebase, idk.

**Comment by Samillion** [comment]
I wonder if it's counting the touch down and up as two downs. Could you do a favor, find the line:
```lua
ne.eventresponder["mbtn_left_down"] = command_callback(user_opts.ch_next_mbtn_left_command)
```

change it to:
```lua
ne.eventresponder["mbtn_left_up"] = command_callback(user_opts.ch_next_mbtn_left_command)
```

Then try to skip forward chapter, still triggers two actions?

**Comment by Keith94** [comment]
Hmm I can't test it properly because it breaks the script (lua error)

![image](https://github.com/user-attachments/assets/38ce8e5d-0264-4566-896a-7b1850145938)

**Comment by Samillion** [comment]
Oops lol. I'll create a branch and link ya, sorry about that.

**Comment by Keith94** [comment]
Aha that's fine. Not sure why it just broke or if I did something wrong.

**Comment by Samillion** [comment]
Could you try the skip/jump buttons with this please:
https://github.com/Samillion/ModernZ/blob/dev_touchpad_up/modernz.lua

**Comment by Keith94** [comment]
With a regular mouse it will appear normal, but only touchpad input crashes it.

**Comment by Samillion** [comment]
😱  oh wow, ok, could you run the following please:

```
mpv --input-test --idle --force-window
```

In that mode, when you tap, what keybind is it using? and with a  single tap, what does it show/trigger?

**Comment by Samillion** [comment]
Sorry, forgot to say to test it with the normal modernz, not the branch I linked.

**Comment by Keith94** [comment]
![image](https://github.com/user-attachments/assets/1b00faed-baf2-4c82-9a0b-7a61f919bec6)

It returns the same text with both regular click and tap

**Comment by Samillion** [comment]
Strange. It's working correctly, keybinding 5 is:
```lua
    {"mbtn_left",           function() process_event("mbtn_left", "up") end,
                            function() process_event("mbtn_left", "down")  end},
```

and 12 is:
```lua
    {"mbtn_left_dbl",       "ignore"},
```

So the skip/jump buttons themselves are causing a double trigger somehow, it's not the keybinds.

This most likely something simple that my eye is not catching at the moment, I'll get back to ya on this.

**Comment by Keith94** [comment]
Sounds good & thanks for the prompt replies

**Comment by Samillion** [comment]
**Self reminder:** remove these two locals
**Reason:** double declaration, either remnant of past or mistake, either way, not needed. Test to be sure.

https://github.com/Samillion/ModernZ/blob/9718605a7e3ecb3481317c06d3ef41d26e18d5cd/modernz.lua#L1663-L1665

I'll go sleep now, then when tomorrow hopefully my two braincells will fix this. xD

**Comment by Samillion** [comment]
Grrrr, another reminder: (╯°□°）╯︵ ┻━┻
- remove nested checks to show/hide in elements based on opts (ie: `user_opts.showjump`). Only needed in layout.

Sorry, finding stuff that needs to be done while tracking bug in this issue, so I'm taking advantage of it to not forget. 😅

**Comment by Samillion** [comment]
https://github.com/Samillion/ModernZ/blob/dev_redundantopts_remove_102324/modernz.lua

**Comment by Samillion** [comment]
I hate to ask, but just to be absolutely sure. Are you certain it's not your touchpad sending double clicks? I'm not denying the bug, just want to be sure.

I tested with a [Logitech K400](https://www.logitech.com/en-us/products/keyboards/k400-plus-touchpad-keyboard.920-007119.html) and can't reproduce.

<p>
<img width="40%" src="https://github.com/user-attachments/assets/7053160c-f6a7-4d3d-a113-2d34450a6df8">
</p>

https://github.com/user-attachments/assets/f31f7cc5-1abe-417c-8623-ade31c026e04

Hmm, but you said it doesn't happen on stock, nvm.... yeah. Ok, this needs investigating.

**Comment by Keith94** [comment]
I don't think so because the input test was only showing MBTN_LEFT. It happens on another laptop too.
