### ISSUE TITLE
osc-visibility set to always is broken

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#86]
1. Add `y script-message-to modernz osc-visibility always`
2. Play video
3. Press `y`
4. Move mouse cursor over video

The OSC goes away on mouse move ;-;

*Default osc doesn't exhibit the issue*

**Comment by Samillion** [comment]
Should be fixed here, would you mind testing? https://github.com/Samillion/ModernZ/blob/dev_visibility_fix/modernz.lua

I've tested with the following:
- Keybind to set visibility mode to `always`
- `keeponpause=yes` (which is visibility mode `always`, on pause)
- tested to see that interactive lists properly show and hide osc even in the always state

**Comment by Keith94** [comment]
Ya, you nailed it again. 😄 

Nitpick: When closing an interactive list, the osc doesn't pop up right away, but it does after mouse movement.
