### ISSUE TITLE
bottomhover doesn't honor hidetimeout

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#87]
1. set `bottomhover=yes`
2. set `hidetimeout=2500`
3. play video and move mouse to and away from osc

Expected:
osc hides after 2500 ms

Actual:
osc hides immediately

Or maybe I have it backwards and the actual behavior is expected. Let me know if I'm wrong.

**Comment by Samillion** [comment]
Hmmm, this happens with both bottomhover set to yes or no.

The behavior I'm observing is:
- First show/hide is correct
- Every other show/hide, it hides immediately when mouse leaves the show area

So down the road hidetimeout is being reset to a negative value or 0. Math. I have to do math..... I hate match 😢 

![227004302](https://github.com/user-attachments/assets/a271de67-c39e-412e-bb82-05b6b58aeb90)

**Comment by Samillion** [comment]
Ooosh. This is a bug that goes back to the very first modern OSC
https://github.com/maoiscat/mpv-osc-modern/pull/46

**Comment by Samillion** [comment]
Could you try this, please:
https://github.com/Samillion/ModernZ/blob/dev_hidetimeout_241024/modernz.lua

**Behavior: `bottomhover=no`**
- If mouse leaves window or stops moving inside window, OSC will hide as per `hidetimeout` value

**Behavior: `bottomhover=yes`**
- If mouse leaves window, OSC will hide as per `hidetimeout` value
- If mouse leaves `bottomhover zone`, inside window, OSC hides immediately

**Changed:**
```lua
local function mouse_leave()
    state.touchtime = nil  

    if get_hidetimeout() >= 0 and get_touchtimeout() <= 0 then
        local elapsed_time = mp.get_time() - state.showtime
        
        if elapsed_time >= (get_hidetimeout() / 1000) then
            hide_osc()
        end
    end

    -- reset mouse position
    state.last_mouseX, state.last_mouseY = nil, nil
    state.mouse_in_window = false
end
```

**Comment by Samillion** [comment]
Try this one, please: https://github.com/Samillion/ModernZ/blob/dev_hidetimeout_fix/modernz.lua

Behavior:
Fully respects `hidetimeout` value, whether `bottomhover` is set to `yes` or `no`.

**Comment by Keith94** [comment]
Works perfectly! Thanks. If I find any weirdness  later I'll be sure to let you know
