### ISSUE TITLE
Add option to enable persistent progress bar based on window behavior

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#98]
I know the hotkey exists but it would be nice to have an option(s) to automatically enable persistentprogress based on the state/mode of the mpv window:

- Enable in window mode only
- Enable in pinned window only
- Fullscreen only? (If needed)

**Comment by Samillion** [comment]
Something like this?
```lua
auto_persistentbar = "no-border",                  -- automatic mode to show persistent progress bar. window, no-border, fullscreen, disable
```

**Comment by Keith94** [comment]
That should work great. Can it accept multiple values?

**Comment by Samillion** [comment]
To address "no-border and fullscreen"? If so, I can create a mode for that.

The reason I would like to keep it simple is to not bloat the code. As having that accept multiple values, would require a for loop validation. Which isn't too bad. Give me a day or so to think of a solid implementation, please.

Specifically, after this PR is merged: https://github.com/Samillion/ModernZ/pull/97

**Comment by Keith94** [comment]
Of course, I totally agree that less bloat the better. For that specifically, didn't know if it would add a lot of bloat since I'm not a programmer 😆 

Do what you think is best though.

**Comment by Keith94** [comment]
Sorry, I was gonna add that my desired use case was to have it enabled for windowed and noborder/pinned modes only, but don't know if that's achieved with a single value

**Comment by Samillion** [comment]
Should be functional here:
https://github.com/Samillion/ModernZ/blob/dev_persistbar_scriptmsg/modernz.lua

Usage by applying auto profiles in `mpv.conf`

**Example auto-profile:**
```ini
[Persistent-Bar]
    profile-desc=Enable persistent bar on window pin and fullscreen
    profile-cond=ontop and ontop == true or fullscreen
    profile-restore=copy-equal
    input-commands=script-message-to modernz persistent-progress yes

[Persistent-Bar-Off]
    profile-desc=Disable persistent bar when not pinned or not fullscreen
    profile-cond=not ontop or ontop == false or not fullscreen
    profile-restore=copy-equal
    input-commands=script-message-to modernz persistent-progress no
```

That way, you can change it however you like using `profile-cond` as the controller.

**Comment by Keith94** [comment]
Dude, you're a legend.. thanks!
Config is perfectly functional here. :)

**Comment by Samillion** [comment]
Awesome! Really glad you liked this implementation. I figured this way it can cover every possible scenario out there.

**Comment by Keith94** [comment]
Where can I donate? xD You deserve a donation button for the hard work.

**Comment by Samillion** [comment]
😻 That means a lot. Your testing and feedback is more than I could ever ask for, beauty of open source. We all share it free of charge.

**Comment by Samillion** [comment]
A better auto profile:
```ini
[Persistent-Bar]
    profile-desc=Enable persistent bar on window pin and fullscreen
    profile-cond=ontop and ontop == true or fullscreen
    profile-restore=copy-equal
    script-opts-append=modernz-persistentprogress=yes
```

**Comment by Samillion** [comment]
I reverted the `script-message` addition. Relying on `script-opts` is a much better result.

You can basically adjust all options of ModernZ with `script-opts-append`:
```ini
[ModernZ-Custom]
    profile-desc=Apply ModernZ options on pin or fullscreen
    profile-cond=ontop and ontop == true or fullscreen
    profile-restore=copy-equal
    script-opts-append=modernz-persistentprogress=yes
    script-opts-append=modernz-seekbarfg_color=#FF0000
    script-opts-append=modernz-bottomhover=no
```
